### ISSUE TITLE
<C-n> to search next word with word boundaries like * does

### ISSUE THREAD

**Issue by balta2ar** [terryma/vim-multiple-cursors#104]
`*` command searches for the current word. To make sure it's actually a word, it adds boundaries: `/\<current_word\>/`. In contrast, `g*` does not add boundaries: `/current_word`. At the moment, `<C-n>` acts like `g*`. I'd like to have both behaviors available. For my use cases it feels like searching with word boundary is a better candidate for the default behavior of `<C-n>`.

This problem occurs when I have a function like that:
```
def foo(bar):
    new_bar = bar.clone()
```

When I put my cursor on `bar` argument and press `<C-n>`, `new_bar` gets partially selected too, which is undesirable.

For the consistency I'd like `<C-n>` to search with word boundaries (as `*` does), and, say, `<C-N>` without boundaries (as `g*` does).

**Comment by faceleg** [comment]
Discussion moved to PR.
