### ISSUE TITLE
How to reproduce the secode git???

### ISSUE THREAD

**Issue by hanhaoxian** [terryma/vim-multiple-cursors#106]
for default config, I wonder how to achive the second gif that select multi line at its start position????

**Comment by CreativLogic** [comment]
[#39](https://github.com/terryma/vim-multiple-cursors/issues/39) as linked in the readme.

### Example 2

+ select the line with V
+ go to the end of the file with G
+ press <C-n> to add a cursor at the beginning of every line and move to normal mode
+ press I to insert at the beginning of the line
+ type ", move to end of line with <C-e>, type another " followed by ,
+ move every cursor down one line with <C-j>(this is a custom mapping of mine in Insert mode)
+ hit <BS>, now all the words are on the same line
+ the rest is just normal Vim

**Comment by hanhaoxian** [comment]
thank you, I found the wanted from you ref link.
