### ISSUE TITLE
Error messages when using j,k,l,h after selection multiple words

### ISSUE THREAD

**Issue by julianvargasalvarez** [terryma/vim-multiple-cursors#11]
I press Control-n several times to select a word, the I press any of the movement keys and I see this:

   Error while processing function <snr>59_apply_user_input_next..385
   E488: Trailing characters
   E488: Trailing characters

but the movement works. This is what I have in my .vim directory:
/Users/julian/.vim
├── after
│   └── syntax
│       ├── haml.vim
│       └── html.vim
├── autoload
│   ├── pathogen.vim
│   ├── rails.vim
│   └── zencoding.vim
├── bundle
│   ├── ctrlp.vim
│   │   ├── autoload
│   │   │   ├── ctrlp
│   │   │   │   ├── bookmarkdir.vim
│   │   │   │   ├── buffertag.vim
│   │   │   │   ├── changes.vim
│   │   │   │   ├── dir.vim
│   │   │   │   ├── line.vim
│   │   │   │   ├── mixed.vim
│   │   │   │   ├── mrufiles.vim
│   │   │   │   ├── quickfix.vim
│   │   │   │   ├── rtscript.vim
│   │   │   │   ├── tag.vim
│   │   │   │   ├── undo.vim
│   │   │   │   └── utils.vim
│   │   │   └── ctrlp.vim
│   │   ├── plugin
│   │   │   └── ctrlp.vim
│   │   └── readme.md
│   ├── desert.vim
│   │   ├── README
│   │   └── desert.vim
│   ├── nerdtree
│   │   ├── README.markdown
│   │   ├── autoload
│   │   │   └── nerdtree.vim
│   │   ├── nerdtree_plugin
│   │   │   ├── exec_menuitem.vim
│   │   │   └── fs_menu.vim
│   │   ├── plugin
│   │   │   ├── NERD_tree.vim
│   │   │   └── nerdtree
│   │   │       ├── bookmark.vim
│   │   │       ├── creator.vim
│   │   │       ├── key_map.vim
│   │   │       ├── menu_controller.vim
│   │   │       ├── menu_item.vim
│   │   │       ├── opener.vim
│   │   │       ├── path.vim
│   │   │       ├── tree_dir_node.vim
│   │   │       └── tree_file_node.vim
│   │   └── syntax
│   │       └── nerdtree.vim
│   ├── supertab
│   │   ├── Makefile
│   │   ├── README.rst
│   │   └── plugin
│   │       └── supertab.vim
│   ├── vim-fugitive
│   │   ├── README.markdown
│   │   └── plugin
│   │       └── fugitive.vim
│   ├── vim-multiple-cursors
│   │   ├── CHANGELOG.md
│   │   ├── MIT-LICENSE.txt
│   │   ├── README.md
│   │   ├── assets
│   │   │   ├── example1.gif
│   │   │   ├── example2.gif
│   │   │   └── example3.gif
│   │   ├── autoload
│   │   │   └── multiple_cursors.vim
│   │   ├── doc
│   │   │   ├── multiple_cursors.txt
│   │   │   └── tags
│   │   └── plugin
│   │       └── multiple_cursors.vim
│   ├── vim-sensible
│   │   ├── README.markdown
│   │   └── plugin
│   │       └── sensible.vim
│   └── vim-surround
│       ├── README.markdown
│       └── plugin
│           └── surround.vim
├── compiler
│   └── coffee.vim
├── doc
│   ├── coffee-script.txt
│   ├── rails.txt
│   ├── tags
│   └── zencoding.txt
├── ftdetect
│   ├── coffee.vim
│   └── eco.vim
├── ftplugin
│   └── coffee.vim
├── indent
│   └── coffee.vim
├── plugin
│   ├── rails.vim
│   └── zencoding.vim
└── syntax
    ├── coffee.vim
    └── eco.vim

35 directories, 69 files

And this is my vimrc

if v:progname =~? "evim"
  finish
endif

set nocompatible
set backspace=indent,eol,start

if has("vms")
  set nobackup      " do not keep a backup file, use versions instead
else
  set backup        " keep a backup file
endif

set history=1000        " keep 50 lines of command line history
set ruler       " show the cursor position all the time
set showcmd     " display incomplete commands
set incsearch       " do incremental searching

map Q gq
inoremap <C-U> <C-G>u<C-U>
syntax on
set hlsearch
augroup vimrcEx
au!
autocmd FileType text setlocal textwidth=78
autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

  set autoindent        " always set autoindenting on

if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
          \ | wincmd p | diffthis
endif
au BufRead,BufNewFile *.rabl setf ruby
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set colorcolumn=120
set number
hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>

" Pathogen
call pathogen#infect()
call pathogen#helptags()

set statusline=%<\ %n:%f\ %m%r%y%=%-35.(line:\ %l\ of\ %L,\ col:\ %c%V\ (%P)%)

set mousehide
set ignorecase
set nowrap
set cursorline
set softtabstop=2

set background=dark
colorscheme desert

nmap <Leader>: :%s/:([a-z_0-9]+)\s+=>/\1:/g<CR>
set autoread " Auto-reload buffers when file changed on disk
set backupdir=~/.vim_backup    " where to put backup files.
set directory=~/.vim_temp      " where to put swap files.
let mapleader=","

**Comment by cheshir** [comment]
Seems like problem has come back.
I press <C-n> several times to select a word, the I go to the insert mode ("I") and write any symbol. Error message:

> line   18:
> E488: Trailing characters
> Error detected while processing function <SNR>90_process_user_input:

I'm using internal OSX vim.
OSX version: 1011.4
[My vim config](https://github.com/cheshir/vim-config)
