### ISSUE TITLE
Add g:multicursor_visual_maps as analogy to g:multicursor_normal_maps

### ISSUE THREAD

**Issue by balta2ar** [terryma/vim-multiple-cursors#111]
I think it might be handy to be able to use selection (and later yanking) with motions such as `i(`, `a(` in Visual mode. Even though it can be emulated with more keystrokes (`da(`, `<Esc>`, `u`) once #89 is implemented, it's nice to have it on its own.

@eapache What do you think? Do you think it could be as simple as `g:multicursor_normal_maps`?

**Comment by eapache** [comment]
Yes, I suspect it might be. In fact looking at that code again (in `display_error`), it doesn't even check the mode which is probably a bug (I wonder if you put those keys in your `normal_maps` if they would work in visual mode already :P)

**Comment by balta2ar** [comment]
Unfortunately, no :( I tried to add `i` to `normal_maps` but pressing `i` in Visual mode switches it to Insert mode.

**Comment by eapache** [comment]
I'm not sure how pressing `i` in visual mode would switch to insert - it doesn't to that in normal vim at all...

**Comment by balta2ar** [comment]
I'm not making that up, try it yourself :)

If I put only `let g:multi_cursor_normal_maps = {'d': 1, 'c': 1}` in my vimrc, I get `Key 'i' cannot be replayed at 3 cursor locations`. If I add more: `let g:multi_cursor_normal_maps = {'d': 1, 'c': 1, 'y': 1, 'i': 1}`, it goes to Insert mode. However, right after `i` it does not say Insert. Only when I start typing, say `w`, it says `-- (insert) --`, just like when you press `Ctrl-o` in Insert mode. So I'm not sure if that's *the* Insert mode.

**Comment by eapache** [comment]
Ah, I think that's a combination of:
- when a key fails to replay in visual mode it accidentally drops you into normal mode (this is probably a bug)
- the code in `display_error` doesn't check the mode (another bug, as I mentioned above) so it replays failed keys

So the `i` gets replayed, and since the first failure drops you into normal mode, the second failure works as intended :P

**Comment by roryokane** [comment]
I think a `g:multicursor_visual_maps` setting is still necessary. When `g:multi_cursor_normal_maps` includes `'f':1`, then <kbd>f</kbd> works fine in Normal mode, but in Visual mode, pressing <kbd>f</kbd> just drops you into Normal mode.

**Comment by balta2ar** [comment]
Yes we totally need this one. Also, I have a suspicion #55 depends on this issue.

**Comment by balta2ar** [comment]
@djjcast Do you think you could take a look at this issue? I think it's finally doable after your recent fixes.
