### ISSUE TITLE
"Setting" a cursor (like using command+click in Sublime)

### ISSUE THREAD

**Issue by aaronbushnell** [terryma/vim-multiple-cursors#118]
Forgive me, I know this is a very noob-ish question.

Is there a way to "set" a multiple cursor using a command of some sort? One thing I like about Sublime is the ability to hold `CMD` and click as often as I want. It allows me to take some educated guesses without writing any regex to select multiple areas.

Does something like this exist in this plugin? Maybe something like this can't even be done in vim, but (if possible) I'd love to have a quick way to arbitrarily drop in cursors.

**Comment by faceleg** [comment]
This is not the plugin you are looking for *waves hands in front of your face*




This is: https://github.com/hlissner/vim-multiedit

**Comment by aaronbushnell** [comment]
Thanks! :D

![sevn4xh](https://cloud.githubusercontent.com/assets/315202/6221857/a23e82ac-b617-11e4-86be-eb476ff98b21.gif)

**Comment by faceleg** [comment]
:dancer:
