### ISSUE TITLE
Can’t use `f` motion in multiple cursor mode

### ISSUE THREAD

**Issue by roryokane** [terryma/vim-multiple-cursors#120]
Whenever I have multiple cursors and hit <kbd>f</kbd> to try to move the cursors to the next occurrence of a character, the cursors exit visual mode, and the following error is displayed:

    Key 'f' cannot be replayed at 2 cursor locations

You can try this with the following example document:

    one find this two
    one two find this

Use `Ctrl-N` twice to select “one” on both lines, and then try `ff` to jump the cursors to the next occurrence of “f” on the line. You will get the error after pressing the first `f`.

Both multiple-cursor-Visual mode and multiple-cursor-Normal mode have this problem.

**Comment by eapache** [comment]
Does it work in normal mode if you add <kbd>f</kbd> to the set of `multi_cursor_normal_maps`?

https://github.com/terryma/vim-multiple-cursors#gmulti_cursor_normal_maps-default-

If so, then fixing it in visual mode should be as simple as finally implementing #111

**Comment by roryokane** [comment]
Yes, <kbd>f</kbd> works in Normal mode after adding the following to my `vimrc`:

```vim
let g:multi_cursor_normal_maps = {'f':1}
```

When I run `:nmap f`, Vim tells me “No mapping found”. So editing `multi_cursor_normal_maps` shouldn’t be necessary to make <kbd>f</kbd> work. Perhaps at first you can internally always add `'f'` to the map, and then you can fix the root problem later.

**Comment by eapache** [comment]
> But f isn’t mapped to anything – when I run :nmap f, I get “No mapping found”. So editing multi_cursor_normal_maps shouldn’t be necessary to make f work.

Unfortunately not true - vim doesn't provide any automatic way to discover what the *default* mappings are that require multiple keys, so the fact that it's not mapped to anything doesn't tell us anything at all. We will add it to `multi_cursor_normal_maps` by default (#21) but I think that's the best we can do.

Perhaps neovim will expose the default mappings programmatically and then we can fix this properly :)

**Comment by roryokane** [comment]
Oh, I was confused by the README’s description that `multi_cursor_normal_maps` says when to “pause for map completion”. I don’t think of the built-in `f` as a “map”, even though it takes multiple keypresses. I wonder if there’s a better way to describe the function of that setting.

Changing the default for `multi_cursor_normal_maps` is fine. I had assumed that you didn’t want to change the current default of `{}`, but if you just haven’t gotten around to adding stuff to it it yet, then adding more keys to it sounds fine.
