### ISSUE TITLE
Very slow performance in large documents

### ISSUE THREAD

**Issue by cheshire** [terryma/vim-multiple-cursors#122]
Hi, I'm running Vim7.4 and latest version of the plugin, but for me the performance in relatively large documents (>1000 lines) is just dreadful: after replacing the multi-selection, every typed letter takes multiple seconds to appear.
Have anyone else had this problem?

**Comment by faceleg** [comment]
Yes!

**Comment by eapache** [comment]
So I just tested this on an 11k-line C file and didn't have any problems. Ubuntu, Vim 7.4.273 on an old but decent computer (2.4Ghz, 3GB ram, etc). I made a dozen cursors and tried a bunch of operations (deleting, typing, etc) and while it wasn't particularly snappy all operations were well under a second. This suggests to me that there is something in your vim setup(s) doing a *lot* of work on every character inserted, which is still present but simply not noticeable in normal operation.

There are two possibilities that come to mind:
- The most common, in my experience, is automatic folding (`foldmethod=syntax` or `foldmethod=indent` in your `.vimrc`) which is, surprisingly, **very** expensive. See https://github.com/Konfekt/FastFold for a discussion and solution.
- Another plugin that operates in insert mode, like snippets (SnipMate et al) or completion (YouCompleteMe et al). Typically these plugins are not useful in multi-cursor mode anyways, so you can use the before/after hooks to disable them appropriately.

If neither of these suggestions work, try adding multiple cursors to a pure vanilla vim (no vimrc and no other plugins) and see if that's faster. If it is, bisect your configuration/plugins to find the culprit.

**Comment by faceleg** [comment]
For me it is a known issue with neocomplete that I just live with.  

So logo as all key presses are entered speed is no issue for me really

**Comment by eapache** [comment]
You can't disable neocomplete in the before/after hooks?

**Comment by faceleg** [comment]
Yes but haven't got around to it. Don't get to so much programming at the moment...

**Comment by faceleg** [comment]
Check the readme, this was fixed. 

https://github.com/terryma/vim-multiple-cursors#multiple_cursors_beforemultiple_cursors_after-default-nothing

**Comment by DelvarWorld** [comment]
FYI, this appears to be how to do it for YouCompleteMe:


    " Called once right before you start selecting multiple cursors
    function! Multiple_cursors_before()
        call youcompleteme#DisableCursorMovedAutocommands()
    endfunction

    " Called once only when the multiple selection is canceled (default <Esc>)
    function! Multiple_cursors_after()
        call youcompleteme#EnableCursorMovedAutocommands()
    endfunction

**Comment by DelvarWorld** [comment]
Also, no matter what i do, multiple cursors is still pretty slow. Up to one second delays when typing in tiny files (< 500 lines). Please reopen this ticket.

**Comment by faceleg** [comment]
Did you try the solution linked to on May 29?

**Comment by DelvarWorld** [comment]
@faceleg see my previous reply :)

**Comment by bchretien** [comment]
@DelvarWorld your solution didn't work (still slow for me), but [this](https://gist.github.com/eapache/0c0abbdb2e810a3f1f4a) did:

```viml
" Experimentally integrate YouCompleteMe with vim-multiple-cursors, otherwise
" the numerous Cursor events cause great slowness
" (https://github.com/kristijanhusak/vim-multiple-cursors/issues/4)

function Multiple_cursors_before()
  let s:old_ycm_whitelist = g:ycm_filetype_whitelist
  let g:ycm_filetype_whitelist = {}
endfunction

function Multiple_cursors_after()
  let g:ycm_filetype_whitelist = s:old_ycm_whitelist
endfunction
```

**Comment by zx1986** [comment]
not working for me :-(

**Comment by uri** [comment]
For me the issue was with folding. I added the following to my vimrc and it was much faster:

```vim
" Called once right before you start selecting multiple cursors
function! Multiple_cursors_before()
  set foldmethod=manual
endfunction

" Called once only when the multiple selection is canceled
function! Multiple_cursors_after()
  set foldmethod=syntax
endfunction
```

**Comment by faceleg** [comment]
@bchretien combining your solution and @DelvarWorld's gave me a huge improvement. @DelvarWorld have you tried it?

**Comment by aemb** [comment]
None of these solutions works for files with about 400 lines. 5 cursors on [this file](https://github.com/aemb/dotfiles/blob/master/.vim/bundles.vim)  just freeze vim and neovim for ever.
```{vim}
  " Called once right before you start selecting multiple cursors
  function! Multiple_cursors_before()
    call youcompleteme#DisableCursorMovedAutocommands()
    set foldmethod=manual
    " let s:old_ycm_whitelist = g:ycm_filetype_whitelist
    " let g:ycm_filetype_whitelist = {} 
    if exists(':NeoCompleteLock')==2
      exe 'NeoCompleteLock'
    endif
  endfunction

  " Called once only when the multiple selection is canceled (default <Esc>)
  function! Multiple_cursors_after()
    call youcompleteme#EnableCursorMovedAutocommands()
    set foldmethod=syntax
    " let g:ycm_filetype_whitelist = s:old_ycm_whitelist
    if exists(':NeoCompleteUnlock')==2
      exe 'NeoCompleteUnlock'
    endif
  endfunction
```

**Comment by pencilcheck** [comment]
Still slow, somehow it is still slow when I have the following script
```
" Called once right before you start selecting multiple cursors
function! Multiple_cursors_before()
  if has('nvim')
    call deoplete#disable()
  endif
  if !has('nvim')
    exe 'NeoCompleteDisable'
  endif
  if exists(':NeoCompleteLock')==2
    exe 'NeoCompleteLock'
  endif
endfunction

" Called once only when the multiple selection is canceled (default <Esc>)
function! Multiple_cursors_after()
  if has('nvim')
    call deoplete#enable()
  endif
  if !has('nvim')
    exe 'NeoCompleteEnable'
  endif
  if exists(':NeoCompleteUnlock')==2
    exe 'NeoCompleteUnlock'
  endif
endfunction

```

I'm on latest stable neovim

**Comment by dyng** [comment]
@pencilcheck Thanks for figuring out the true trouble maker of YankRing. It seems YankRing is always troublesome but I have not found a suitable alternative.
