### ISSUE TITLE
ctrl-n does not match current word well.

### ISSUE THREAD

**Issue by brookhong** [terryma/vim-multiple-cursors#124]
`ctrl-n` on the first `proo_name`, then press `ctrl-n` again, it will jump to the last one, without matching the second.
Looks like that the following char(here it is `)`) after current word is used in the match pattern.

    deff hello(proo_name)
        proo_name ||= "afdb"
        puts(proo_name)
    end

**Comment by s0nspark** [comment]
I see this same behavior on Windows with Vim 7.4 but not on OS X with MacVim 7.4.258. If I can be any help tracing the problem let me know :)

**Comment by CreativLogic** [comment]
Not seeing this problem on OS X MacVim 7.4.622.

**Comment by brookhong** [comment]
I did some study on this issue and the implementation.

For me, the issue comes with gvim on ubuntu and gvim on windows, but not with vim on ubuntu.

If you paste the code snippet above in gvim(which has gui_running), move cursor on the first `proo_name`, type `viw` then `Esc`, the cursor is now on the last char `)`.
But in vim, if you do the same operations, the cursor is on `e`.

That makes getpos("'>") returns [0, 1, 20, 0] in vim, but [0, 1, 21, 0] in gvim, and this is the trouble.

**Comment by kristijanhusak** [comment]
It's maybe problem with regexpengine. Try `:set regexpengine=1`. Default is 0. This sets the old regexp engine. I'm not sure if this is recommended to change, but at least to find the problem.

More info about it `:help 'regexpengine'`

**Comment by brookhong** [comment]
Nope, it has no relationship with regexpengine.

Basically it's caused by difference of vim and gVim.
In vim when you visual select a word, then press `Esc`, cursor sits at end of the word.
In gVim when you visual select a word, then press `Esc`, cursor sits at a char next to the end of the word.

The issue can be fixed in this plugin, but I prefer vim can fix the difference of vim and gVim.

**Comment by brookhong** [comment]
I finally fixed the issue by below setting:

    set selection=inclusive

`selection` is set to `exclusive` in gVim, and `inclusive` in vim.
That's why the plugin works fine in vim but not in gVim by default.

**Comment by balta2ar** [comment]
@brookhong @faceleg I think it's worth mentioning this case and this setting somewhere in readme with hope to help people avoid wasting time investigating it themselves, probably in FAQ or Common Problems/Troubleshooting section. What do you think?

**Comment by justinmk** [comment]
This is really a bug in the plugin. It's common for plugins to work around this. 

The example code at `:h g@` shows this:

```
let sel_save = &selection
let &selection = "inclusive"
...
let &selection = sel_save
let @@ = reg_save
```

**Comment by faceleg** [comment]
@justinmk would we have to add this to every plugin file?

**Comment by balta2ar** [comment]
Please correct me if I'm wrong but I guess it should be another option that is saved when CursorManager is created, like this: https://github.com/terryma/vim-multiple-cursors/blob/master/autoload/multiple_cursors.vim#L362

**Comment by justinmk** [comment]
@balta2ar Something like that, yes.

**Comment by ezequiel** [comment]
@balta2ar @justinmk I created a pull request containing the spoken of bug fix: https://github.com/terryma/vim-multiple-cursors/pull/135

**Comment by balta2ar** [comment]
@ezequiel Hm, you're saving selection but I don't see that you're changing it in a way, that is suitable for the plugin to work, e.g. I don't see something like this:
``` vim
let &selection = "inclusive"
```

Please add unit tests for that case. Make sure they fail without your patch and pass with it.
