### ISSUE TITLE
% MultipleCursorsFind ^

### ISSUE THREAD

**Issue by DrVanScott** [terryma/vim-multiple-cursors#128]
Suppose a buffer containing

    1
    2
    3
    4
    5

% MultipleCursorsFind ^

or 

% MultipleCursorsFind $

give incomplete cursors. Or do i miss something?

**Comment by CreativLogic** [comment]
I get a similar behavior but I'm assuming (and *only* assuming) that `%` and `$` are movements and not findable characters.

What's the desired selection?

If I wanted each line to have a cursor in this instance I would `gg` to the top of the buffer. `VG` to select all the lines and `<C-n>` to a cursor on each line.

**Comment by DrVanScott** [comment]
Am 23. März 2015 18:59:06 MEZ, schrieb Chris Honniball <notifications@github.com>:
>`%` and `$` are movements and not findable characters.
% is a range, meaning "for all lines".
^ is a special Charakter in regular expressions matching "beginning of line".
$ matches "end of line"

>What's the desired selection?
A cursor at the beginning resp. the end of each line.

**Comment by CreativLogic** [comment]
> % is a range, meaning "for all lines".
> ^ is a special Charakter in regular expressions matching "beginning of line".
> $ matches "end of line"

Is this the desired effect?

`:MultipleCursorsFind ^.*$`

**Comment by DrVanScott** [comment]
> :MultipleCursorsFind ^.*$

This is what i would expect for

:MultipleCursorsFind $

or in other words: "set a cursor on each end of line"

In contrast

:MultipleCursorsFind ^

should set a cursor on each begining of line"

Actually my expectations can be seen by using

.$

or

^.

**Comment by faceleg** [comment]
Is this still an issue?

**Comment by DrVanScott** [comment]
Yes, my last comment is still valid. I closed the issue by mistake, therefore i reopened it.
