### ISSUE TITLE
PR-REQUEST By default select with word boundary in Normal mode

### ISSUE THREAD

**Issue by lacombar** [terryma/vim-multiple-cursors#129]
In the following exemple:

```
foo
foo foobar
foo
```

Trying to select the three `foo` will also select `foobar` which is not expected.

**Comment by CreativLogic** [comment]
With the default mappings:

Cursor on first `foo`.

1. <C-n> - Selects first `foo`
2. <C-n> - Selects second `foo`
3. <C-n> - Selects `foo` in `foobar`
4. <C-x> to skips `foo` in `foobar` and selects final `foo`

**Comment by lacombar** [comment]
The <C-x> step is not natural. It should not have been selected at the first place. Moreover, `^foo` assumes the line start with `foo` which might fit the given example, but unlikely to fit real code, say
```
foo
foo foobar foo
foo
```
In this case, `:MultipleCursorFind foo\>` would work. But a more general test case for this issue would be:
```
foo
foo foobar foo barfoo
foo
```
Here the search would be: `:MultipleCursorFind \<foo\>`. This is the core of this issue. The search pattern should be `\<[word below cursor]\>`, not just `[word below cursor]`.

**Comment by balta2ar** [comment]
@lacombar I know that feel, bro. Please read this: https://github.com/terryma/vim-multiple-cursors/pull/105. Is this what you want?

@faceleg I noticed several people mentioning that behavior and expecting it to be default (including me). Maybe it's time to make it default? I remember someone in comments offering that somewhere.

**Comment by faceleg** [comment]
I agree it should be default, enough people have risen up that it seems the obvious choice.

Would the old behaviour be toggle-able via a switch?

**Comment by balta2ar** [comment]
Well, via a two-line configuration as I demonstrated in that PR. It's mentioned in Mapping section of README. We can change default behavior and fix README to instruct how to bring old behavior back in case someone likes it better. If @lacombar confirms it solves his problem, I suggest renaming this issue to "By default select with word boundary in Normal mode" and keeping it open until someone sends a PR (the change shouldn't be that hard). Note that word boundary is not applied in Visual mode, I hope everyone agrees it's not very logical to do that.

**Comment by lacombar** [comment]
```
let g:multi_cursor_start_key='g<C-n>'
let g:multi_cursor_start_word_key='<C-n>'
```

in my `.vimrc` seems to work fine for me.
