### ISSUE TITLE
Replacing selection with newlines is not working correctly

### ISSUE THREAD

**Issue by uri** [terryma/vim-multiple-cursors#134]
Original string:

```
    :account_type, :birth_day, :birth_month, :birth_year, :business_name, :business_number, :city, :employer_id, :postal_code, :region, :social_security_number, :street_address, :street_address_2, :first_name, :last_name, :phone
```

Select ', ' in visual mode then spamming `c-n`, `c` and then `<CR>` produces:

```
    :account_type
    birth
    _daybir
    th_mon
    thbirth_y
    earbusiness
    
    _namebu
    siness_
    nu
    mbercityemployer_i
    dpostal_co
    deregionsoci
    al_sec
    urity_numberstreet_addressstreet_address_2first_namelast_name
    phone
```

#### Expected result

```
    :account_type
    :birth_day
    :birth_month
    :birth_year
    :business_name
    :business_number
    :city
    :employer_id
    :postal_code
    :region
    :social_security_number
    :street_address
    :street_address_2
    :first_name
    :last_name
    :phone
```

**Comment by faceleg** [comment]
Do you have all other plugins turned off?

**Comment by balta2ar** [comment]
I couldn't reproduce the problem in my environment.

**Comment by uri** [comment]
@faceleg I'll try that next.

**Comment by uri** [comment]
Aha! It looks like [supertab](https://github.com/ervandew/supertab) is the culprit!

**Comment by uri** [comment]
Looks like setting the file type to anything before pasting in the string is working for me...

1. `yy` to copy string
1. `:new`
1. `:set ft=asdf`
1. `p`
1. Multicursor...

**Comment by faceleg** [comment]
Still can't reproduce in my env

**Comment by uri** [comment]
Phew took me a while to trace, but I'm 99% sure it has to do with `smartindent`. I had 

    set smartindent

In my `vimrc` *and* tpope/vim-sensible which also set `smartindent`. Removing this makes it work normally.

**Comment by uri** [comment]
Looks like it actually wasn't smartindent. It seems to work in a new buffer, so it might have something to do with me using vim-ruby, or vim-rails.
