### ISSUE TITLE
Trailing characters error in process user input on mac (vim 7.3)

### ISSUE THREAD

**Issue by naggie** [terryma/vim-multiple-cursors#137]
![image](https://cloud.githubusercontent.com/assets/208440/7541103/8ae0744e-f5aa-11e4-95ec-55af6e47e424.png)
![image](https://cloud.githubusercontent.com/assets/208440/7564243/a3e78f20-f7dc-11e4-8cb8-e156c65ed213.png)

I only have this problem on my Mac, since I updated multiple-cursors probably 4-5 months ago.

This happens after the 2nd character when doing a `c` substitution. To reproduce:

1. Create a new buffer containing (for example)
    ```
    beans
    beans
    ```
2.  Press `CTRL+N` twice on the first word in normal mode
3.  Press `c` to change both words at once
4. Type something, eg `fab`. The third character triggers this error.

Versions of things: vim 7.3, multiple cursors 5d23963be369ca9be878c6d64ed52263676f2a60

I confirm that this happens isolated -- no other plugins

**Comment by naggie** [comment]
Upgrading to vim 7.4 works around this issue.

**Comment by balta2ar** [comment]
`Installation` section says "Requires vim 7.4 or later for full functionality".

**Comment by naggie** [comment]
That's a shame considering it used to support 7.3 and I have no choice but to run 7.3 on some of my work systems....


7.3 must be very common. Would you reconsider supporting it?

**Comment by balta2ar** [comment]
There was another vim 7.3 specific issue which led to adding that notice in README.md, so it's not the first time. There are other issues which I'd love to work on but I have no time. Considering that, supporting older vim versions looks very low priority to me. Maybe other contributors have more motivation to fix that. However, your patch is always welcome.

**Comment by jcornil** [comment]
I got same error when I press any of g, b, k, u key.
- Vim 7.4 on Mac.
