### ISSUE TITLE
Too many arguments for function: multiple_cursors#new

### ISSUE THREAD

**Issue by rbudiharso** [terryma/vim-multiple-cursors#139]
I'm using janus with several additional plugin and when I press `ctrl`+`n` I got this error

![screenshot from 2015-05-20 11 13 54](https://cloud.githubusercontent.com/assets/43447/7718913/ec22f106-fee1-11e4-801e-7cc91476161f.png)

Don't know what went wrong, it works the day before and now it doesn't

**Comment by rbudiharso** [comment]
My bad, I accidentally install another vim-multiple-cursor plugin, removing one of them sort it out

**Comment by flov** [comment]
thanks! That actually helped me to realize that I double installed it via Vundle and janus. Another reason not to use janus maybe
