### ISSUE TITLE
Does not respect custom vim cursors

### ISSUE THREAD

**Issue by AndrewRayCode** [terryma/vim-multiple-cursors#142]
First of all, thank you so much for making this plugin.

I have this configuration:

```
set guicursor=n-c:ver30-Cursor/lCursor,ve:ver35-Cursor,o:hor50-Cursor,i-ci:ver25-iCursor/lCursor,r-cr:hor20-Cursor/lCursor,v-sm:block-Cursor
```

It's a bunch of garbage, but it gives me a custom Vim cursor in normal and insert mode. With multiple cursors, I get the generic white block.

**Comment by balta2ar** [comment]
Out of curiosity, could you please take a snapshot of how your cursor looks like in Normal and Insert modes? With your settings I get something that looks like a thin vertical bar in Normal mode and a slightly highlighted letter (transparent cursor) in Insert mode.

**Comment by faceleg** [comment]
Still an issue?
