### ISSUE TITLE
Can't use line completion in cursor mode

### ISSUE THREAD

**Issue by AndrewRayCode** [terryma/vim-multiple-cursors#143]
When in multiple-insert mode, hitting `<ctrl-x><ctrl-l>` (that's a lowercase L) for linewise completion, this is inserted:

```
:call <SNR>161_apply_user_input_next('i')
```

**Comment by faceleg** [comment]
Still an issue?

**Comment by balta2ar** [comment]
Yes, plugin does not support that. I'd tag it "feature request".

**Comment by faceleg** [comment]
I'll try to remember to change enhancement to feature request when I'm back at my computer
