### ISSUE TITLE
Can't use the completion menu in multiple-insert mode

### ISSUE THREAD

**Issue by AndrewRayCode** [terryma/vim-multiple-cursors#144]
`<c-n>` only uses the first completion option in the menu. It will also pop the menu for a split second, then it disappears, and you only get the first completion. I imagine this extends to any completion method, like linewise completion with `<ctrl-x><ctrl-l>`

**Comment by balta2ar** [comment]
I'm occasionally suffering from this restriction too.

**Comment by faceleg** [comment]
Still an issue? If so please provide a vimrc that exhibits the behaviour

**Comment by DelvarWorld** [comment]
@faceleg please stop spamming tickets :)

**Comment by balta2ar** [comment]
Yes this is still an issue. This plugin does not support completion. I wish I did, though.

**Comment by faceleg** [comment]
Oh right yeah. I turned my completion off when multi cursors is active.

**Comment by balta2ar** [comment]
@djjcast Should you wish to contribute more, this is the next biggest problem (to me) in this plugin that I'd like to bring your attention to. I'm not sure how easy it is to fix this one, though. Anyway, feel free to attack any issue you like, this repo really needs love of vimscript gurus.

**Comment by antoinemadec** [comment]
@balta2ar , i don't know. I think it might be a lot of work, but that is definitely a feature I would love to see.
For now, I am going to focus on easy-to-implement features.
Meanwhile, if someone want to tackle that, that'd be great.
Otherwise I will try to look at it in the future, but I don't promise anything.

**Comment by hiberabyss** [comment]
Any update about this issue?

**Comment by balta2ar** [comment]
@hiberabyss If you don't mind changing plugins, here is another one that implements multiple cursors in vim: https://github.com/mg979/vim-visual-multi. It's much faster, feature-rich and completion with multiple cursors is working fine there.
