### ISSUE TITLE
Deletion of end-of-line character is not possible

### ISSUE THREAD

**Issue by sschaef** [terryma/vim-multiple-cursors#146]
Say, we select the following lines:

```
abcd
abcd
abcd
abcd
abcd
```

Pressing `<c-n>` leads to a cursor on each line. If I now press `A` and then `<del>` in order to remove the eol char the result is:

```
abcdbcd
abcdbcd
abcd
```

whereas `abcdabcdabcdabcdabcd` is expected. It looks like it doesn't treat the eol char as a real character.

**Comment by balta2ar** [comment]
In my setup `A` does not even work, it prints `(multiple-cursors-apply):call SNR>192_detect_bad_input()`.

**Comment by faceleg** [comment]
Works as @sschaef described for me

**Comment by sschaef** [comment]
What do you mean by that it works for you as described by me? Can't you see the problem or do you suffer from it as well (just tried it again with the newest version and it still doesn't work).

**Comment by faceleg** [comment]
Sorry, I mean I *do* see the problem, as in "when I do the steps as described it doesn't delete the `eol` character".

**Comment by antoinemadec** [comment]
@sschaef , you'll be glad to learn that this feature has been added to the plugin a few weeks ago.
Update it and that should work out of the box ;)
