### ISSUE TITLE
Feature: MultipleCursorFind against all open buffers?

### ISSUE THREAD

**Issue by PhillipTaylor** [terryma/vim-multiple-cursors#148]
Is it possible to do this?

echo "hello" > /tmp/test{1,2}
vim -o /tmp/test{1,2}
:%sMultipleCursorFind h

and have a cursor in each window so you can edit both documents simultaneously please?

**Comment by faceleg** [comment]
This sounds like a great feature. I'm not saying it is impossible, but I'd be very surprised if it is ever implemented.

**Comment by balta2ar** [comment]
Let's at least tag it "feature request" so it's easier to find it later (just in case).
