### ISSUE TITLE
Does not paste from system clipboard in MacVim

### ISSUE THREAD

**Issue by AndrewRayCode** [terryma/vim-multiple-cursors#150]
In multiple cursor insert mode, hitting splat-v (`⌘-v`) inserts the contents `"+gP` instead of contents of the clipboard.

**Comment by Borissov** [comment]
I fix it with:
```.gvimrc
    macmenu Edit.Paste key=<nop>
```
and create in .vimrc new hotkey with paste

```.vimrc
    nnoremap <D-v> "+gP
```

**Comment by DelvarWorld** [comment]
Why close? Obviously overwriting the system paste behavior is not a solution to this problem

**Comment by faceleg** [comment]
Someone suggested a fix, you failed to reply. Issues need tidying up. Seems to have prompted you to come back and reject the suggested fix - since you've bothered to do this I will reopen.

**Comment by DelvarWorld** [comment]
@faceleg can you clarify your relationship to this project? Closing an unfixed, major issue for the motivation of "tidying up" doesn't make sense to me in an open source project. I "bothered" to file this issue in the first place, and I don't understand why it not being fixed over time is a reason to close it.

**Comment by DelvarWorld** [comment]
I would also add being condescending to people who take the time to file tickets voluntarily and then dismissing their efforts is a poor community strategy. This project is vibrantly buggy which is why there are many open issues.

**Comment by faceleg** [comment]
There is no way I'm entering an argument with you on this. I close an issue. You came back telling me it should not be closed. I reopened the issue. 

We welcome your input.

**Comment by faceleg** [comment]
If my communications have offended you, I apologise and will do my best to ensure I don't do so again.

**Comment by Borissov** [comment]
All command key combination have the same problem. Not only paste.... I override all command key combinations.

**Comment by nickbarth** [comment]
I'm seeing this issue on OSX in terminal vim as well. But adding this line to the `.vimrc` fixes it without having to remap `<D-v>`:

```set t_BE=```

https://vimhelp.org/term.txt.html#xterm-bracketed-paste
