### ISSUE TITLE
Mapping to select all occurances

### ISSUE THREAD

**Issue by AndrewRayCode** [terryma/vim-multiple-cursors#151]
Sublime text has Ctrl+Command+G to select all matches in the current document. As far as I can tell there's no easy way to do this with vim multiple cursors. I wrote a function to do it, but I don't think it's quite PR worthy https://github.com/AndrewRayCode/configs/blob/3a22afc584f520fdd89d4689ff662c5440c54f3d/.vimrc#L207-L241 . Maybe a good starting place. It adds a `<leader>fa` mapping that works both in visual mode and normal mode.

**Comment by faceleg** [comment]
Part of me wants this in core, part of me thinks it is good as a function people can paste into their vimrc if they wan it...

**Comment by guiltry** [comment]
+1 to have this feature.

**Comment by faceleg** [comment]
@DelvarWorld mind if I copy-paste this into the plugin *or* the readme?

@aschrab @eapache @balta2ar are any of you vehemently against this being added to core?

**Comment by balta2ar** [comment]
I'm OK with that. Though I'm hesitant about the constant 15. I'm not sure such threshold is needed but if in fact it is, then maybe 15 should be configurable.

Also I don't think we should bind it to any key by default. Just mention in the docs and give an example is enough, I think.

**Comment by faceleg** [comment]
Understood and agreed

**Comment by uri** [comment]
Was this ever added to the plugin or readme? I'm not seeing this anywhere.

**Comment by faceleg** [comment]
Neither - waiting for a PR

**Comment by hems** [comment]
indeed find all would be very valuable and i believe it should be a core function specially considering the readme compares itself with Sublime Text which has this function by default!

**Comment by 3rd3** [comment]
I also frequently use this in Emacs and Sublime Text. It lets you perform more complicated replacements you could also do with search/replace, but in a more interactive and faster way. For example, if one wants to convert a getter `self.getConfig(key)` into a dictionary `self._config[key]`, one can simply select all occurrences `getConfig`, then type away the changes using the `e`, `b`, `f` and surround movements. One often even has a couple of samples in view to see how the edits are turning out. It would be nice, of course, if one could check all edits at each cursor when exiting the multiple cursor mode, similar to the `/c` option for replacements.

**Comment by hems** [comment]
@3rd3 i like the idea of ctrl+n and then ctrl+x to skip! so most of the times i do one by one, but i think in honour to ST amazing replacement would be nice to have a bind to change all!
