### ISSUE TITLE
`0` does not go to beginning of line in normal mode

### ISSUE THREAD

**Issue by benjie** [terryma/vim-multiple-cursors#152]
`^` can be used to go to the first non-whitespace character in the line. `0` and `^` both work correctly in visual mode.

**Comment by rodfersou** [comment]
I have the same issue just when I am into insert mode and go back to normal mode after an `<Esc>` (using let g:multi_cursor_exit_from_insert_mode=0)

Then to solve here I need to get into insert mode again and go back into normal mode with `<Esc>`

I'm not sure if my problem is related, I'm using vim into the terminal, not graphical mode.

but if I start with fresh cursors `0` works well for me.

**Comment by faceleg** [comment]
Confirmed this is a bug. To reproduce:

1. Set `let g:multi_cursor_exit_from_insert_mode=0`
2. Select more than one region
2. `esc` to enter normal mode
3. Press `0` to go to start of lines
4. Observe fail

**Comment by ninrod** [comment]
Isn't [this](https://github.com/terryma/vim-multiple-cursors/blob/master/autoload/multiple_cursors.vim#L1026) the culprit?

**Comment by ninrod** [comment]
I think I've fixed it in #207
