### ISSUE TITLE
Question: How to skip a selection 

### ISSUE THREAD

**Issue by zhangchiqing** [terryma/vim-multiple-cursors#156]
When pressing Ctrl + n, I'm adding more matched words into the multi-selection. How can I skip a selection that I don't want? 

For example, I have the following text, the first `aa` is selected

`aa` bb cc
aa bb
aa

I press Ctrl + n, the second `aa` is selected as below.

`aa` bb cc
`aa` bb
aa

Now, I want to cancel the second `aa`, and select the third `aa`. How can I do it? I tried Shift + Ctrl + n, but doesn't work.

`aa` bb cc
aa bb
`aa`

**Comment by balta2ar** [comment]
In default settings Ctrl + x does what you want.

**Comment by zhangchiqing** [comment]
Awesome! Thanks @balta2ar

**Comment by FinallyFinancialFreedom** [comment]
how to just cancel the current select and return to previous select position?
