### ISSUE TITLE
Plugin breaks FN (N=1,2,...) key bindings

### ISSUE THREAD

**Issue by delminskii** [terryma/vim-multiple-cursors#158]
I have key bindings for some plugins in my `.vimrc`:

<pre>
                                                                         
113 " NERDTree settings                                                              
114 " ==============================                                                 
115 map F3 :NERDTreeToggle CR                                                    
116 let NERDTreeIgnore = ['\.pyc$']                                                  
117                                                                                  
118                                                                                  
119 " ==============================                                                 
120 " TagBar settings                                                                
121 " ==============================                                                 
122 map F4 :TagbarToggle CR                                                      
123 let g:tagbar_autofocus = 1                  " autofocus on tagbar when it opens
</pre>

PS: F3, F4 and CR are the <F3>, <F4> and <CR>, of course;
When vim loads your plugin, the last breaks these bindings. Is there any redefinings? Or maybe I haven't read description to this plugin more accurately yet...

**Comment by delminskii** [comment]
With those options which are showed in this topic, works the next only: \F3, \F4
But it's hard to press leader every time; the leader isn't a poblem's solution here.

**Comment by faceleg** [comment]
Please see https://github.com/terryma/vim-multiple-cursors/blob/master/ISSUES.md and provide more info

**Comment by azamat-sharapov** [comment]
Are you using vim-plug and plugging it like `Plug 'vim-multiple-cursors'`? If so, try changing it to `Plug 'terryma/vim-multiple-cursors'`, run `:PlugClean` and then `:PlugUpdate` to fetch them from github, otherwise it defaults to vimscripts, which is breaking things (maybe vim-multiple-cursors is out of date in on vimscripts site).

**Comment by antoinemadec** [comment]
Everything works find with the up-to-date plugin.
Closing the issue.
