### ISSUE TITLE
Error detected while processing function <SNR>61_process_user_input

### ISSUE THREAD

**Issue by blacklab** [terryma/vim-multiple-cursors#159]
The plugin works great on Linux but on Mac I get the following error when I want to enter an 'u', 'k', 'g' or 'b':

    Error detected while processing function <SNR>61_process_user_input:
    line   18:
    E488: Trailing characters

Any ideas? Is this a bug or a configuration on my sight?

**Comment by balta2ar** [comment]
Make sure you've using vim 7.4, not vim 7.3 on Mac.

**Comment by blacklab** [comment]
I install the newest vim version with brew. Worked great. Thanks!
