### ISSUE TITLE
Pressing 'a' in normal mode inserts <Plug>(multiple-cursors-apply)

### ISSUE THREAD

**Issue by SageEx** [terryma/vim-multiple-cursors#160]
After highlighting multiple words, and entering normal mode( by pressing 'v' ) pressing  'a' inserts <Plug>(multiple-cursors-apply) twice and the plugin doesn't work.
My settings in .vimrc

    let g:multi_cursor_next_key='<C-a>'
    let g:multi_cursor_prev_key='<C-s>'
    let g:multi_cursor_skip_key='<C-d>'
    let g:multi_cursor_quit_key='<Esc>'

I use neocomplete & have added this

    " Called once right before you start selecting multiple cursors
    function! Multiple_cursors_before()
      if exists(':NeoCompleteLock')==2
        exe 'NeoCompleteLock'
      endif
    endfunction

    " Called once only when the multiple selection is canceled (default <Esc>)
    function! Multiple_cursors_after()
      if exists(':NeoCompleteUnlock')==2
        exe 'NeoCompleteUnlock'
      endif
    endfunction
in my .vimrc

The error : 

![screenshot from 2015-09-09 04-21-31](https://cloud.githubusercontent.com/assets/7141867/9749471/c2e8ab3e-56aa-11e5-9926-e058d21072e0.png)

**Comment by balta2ar** [comment]
1. Make sure you're using latest version of vim (or at least 7.4)
2. Check if you have other mappings for `a` in Normal mode
9 сент. 2015 г. 1:58 AM пользователь "Arindam Banerjee" <
notifications@github.com> написал:

**Comment by SageEx** [comment]
1) Vim version - 7.4 patches 1-854
2) normal-mode `a` is not mapped to anything.
In fact the same problem happens when pressing i or I or A - anything that takes to insert mode from normal mode.

**Comment by balta2ar** [comment]
`i` and `a` should work. `I` and `A` are known to be not working, this is expected.

This must be something about your configuration and a mixture of plugins. Try turning off some plugins and check again. Keep disabling plugins until it starts working.

**Comment by SageEx** [comment]
Even with all plugins turned off the problem persists. Seems like it is an issue with some setting in my .vimrc.

After some commenting & restarting vim the error lies in these lines

     if has("autocmd")
         au InsertEnter *
                      \ if v:insertmode == 'i' |
                      \   silent execute "!gnome-terminal-cursor-shape.sh ibeam" |
                      \ elseif v:insertmode == 'r' |
                      \   silent execute "!gnome-terminal-cursor-shape.sh underline" |
                      \ endif
          au InsertLeave * silent execute "!gnome-terminal-cursor-shape.sh block"
          au VimEnter * silent execute "!gnome-terminal-cursor-shape.sh block"
          au VimLeave * silent execute "!gnome-terminal-cursor-shape.sh underline"
      endif

Contents of gnome-terminal-cursor-shape.sh

    #!/bin/sh
    DEFAULTPROF=`dconf read /org/gnome/terminal/legacy/profiles:/default`
    DEFAULTPROF=`echo "$DEFAULTPROF" | sed -e "s/^'/:/" -e "s/'$//"`
    dconf write /org/gnome/terminal/legacy/profiles:/$DEFAULTPROF/cursor-shape "'$1'"

This file just changes cursor in gnome-terminal according to modes. Taken from vim.wikia.com(http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes).

This is quite important for my workflow - 
 Any ideas how to rectify this ?

**Comment by SageEx** [comment]
Interestingly, the gnome-terminal is VTE compatible - 
thus the following code 

    let &t_SI = "\<Esc>[6 q"
    let &t_SR = "\<Esc>[4 q"
    let &t_EI = "\<Esc>[2 q"

plays nicely with the multiple-cursors.

I have replaced this with the previous code & everything works. 

Still, any idea what was happening in the previous code ?

**Comment by aj07mm** [comment]
same here. GNOME Terminal 3.18.3

**Comment by SageEx** [comment]
@aj07mm Are you also using the dconf settings to change the cursor ? Try the VTE settings to change the cursor, it works with gnome-terminal.
