### ISSUE TITLE
Messes up nocp/nocompatible, maps arrow to A,B,C,D

### ISSUE THREAD

**Issue by perich** [terryma/vim-multiple-cursors#163]
I have tested everything else in my ~/.vimrc file, only when this is installed to I get the issue. When I open a file, the down key will delete the first two lines and the arrows are mapped to A,B,C,D

[Screen capture video](http://tinypic.com/player.php?v=29o322r%3E&s=8#.Vgrd8xOqqko)

It only does this in insert mode. Anyone know how to fix this?

      1 set nocp
      2 filetype off
      3 
      4 set rtp+=~/.vim/bundle/Vundle.vim
      5 call vundle#begin()
      6 " Install from command line with: vim +PluginInstall +qall
      7 " Install from VIM with :PluginInstall
      8 Plugin 'VundleVim/Vundle.vim'
      9 Plugin 'vim-gitgutter'
     10 Plugin 'vim-multiple-cursors'
     11 call vundle#end() 
     12 filetype plugin indent on 
     13 
     14 
     15 syntax enable
     16 colorscheme monokai
     17 set number
     18 set ts=2 sts=2 sw=2 expandtab

**Comment by balta2ar** [comment]
Just to confirm, are you using the latest version of vim? Or at least 7.4?

**Comment by perich** [comment]
@balta2ar Yes, 7.4.769

**Comment by balta2ar** [comment]
I'm not familiar with Vundle syntax, but shouldn't it be `'terryma/vim-multiple-cursors'` (this is how it looks in my NeoBundle section)? Anyway, please also check you're using version from this repo. Sorry for giving such an obvious and dumb advices, but please check it just in case.

Another question, why first lines in your vimrc are there? Why not after the Vundle section?

**Comment by perich** [comment]
@balta2ar 

> Sorry for giving such an obvious and dumb advices

Dumb advice helps dumb people like me. This worked thanks. I'm new to Vim, switching from ST2 so this package control is all new to me.

In case anyone else is having the same issue. Here is my new ~/.vimrc

     1 set rtp+=~/.vim/bundle/Vundle.vim
     2 call vundle#begin()
     3 " Install from command line with: vim +PluginInstall +qall
     4 " Install from VIM with :PluginInstall
     5 
     6 set nocp
     7 filetype off
     8 
     9 Plugin 'VundleVim/Vundle.vim'
    10 Plugin 'vim-gitgutter'
    11 Plugin 'terryma/vim-multiple-cursors'
    12 
    13 syntax enable
    14 colorscheme monokai
    15 set number
    16 set ts=2 sts=2 sw=2 expandtab
    17 
    18 call vundle#end()        
    19 filetype plugin indent on
