### ISSUE TITLE
Lines are replaced by some Vim commands

### ISSUE THREAD

**Issue by schoettl** [terryma/vim-multiple-cursors#167]
I want to format a file, this line:

    build-depends:      base, hspec, QuickCheck, rangit, AC-Angle, HUnit, utility-ht

should be:

    build-depends:      base
                      , hspec
                      , QuickCheck
                      , rangit
                        ...

I tried this: `0f,v<C-n>…<C-n>I<CR>`

Result: `:call <SNR>68_apply_user_input_next('i')` (in each new line)

I also tried this: `0f,<C-v><C-n>…<C-n>I<CR>`

Same result.

I also tried insert with `i` (lower case): `cannot be replayed at 3 curser positions`

What am I doing wrong?

**Comment by eapache** [comment]
Creating multiple cursors leaves you in vim's visual block mode, not in vim's normal mode. Pressing `i` in visual block mode in vim does nothing. To get to insert mode properly, you'll need to press `v` first to switch from visual-block to normal, e.g. something like

`<C-n>...<C-n>vi<CR>`.

**Comment by schoettl** [comment]
That works. Thank you!

I still do not understand why capital `I` does not work. It usually does in Vim's visual block mode.

Also I would find it incredibly useful if the Vim command sequence was written below each GIF in the README. It took me a while to find out that I first have to press `v` on the comma to be able to use `<C-n>` (like in the GIF). I can try to make a patch for the README.

**Comment by eapache** [comment]
The lack of `I` is bug, #55 which I've never been able to figure out. PRs to improve the README would be very welcome!
