### ISSUE TITLE
vim starts in replace mode

### ISSUE THREAD

**Issue by louwers** [terryma/vim-multiple-cursors#169]
With this plugin enabled, vim starts in replace mode (when starting with `vim`) or vim starts with the command `2c` in the queued commands (also, my Terminal beeps twice).

These problems go away when uncommenting `Plugin 'vim-multiple-cursors'`...

Edit: no, I do not have `<Esc>` or in fact any other key remapped.
Edit2: This plugin is causing all kinds of weird problems! When I go down with the arrow key, vim goes into insert mode and enters a newline and a B. (When I go up it's an A, left D, right C).

**Comment by louwers** [comment]
This seems to be the same bug. https://github.com/terryma/vim-multiple-cursors/issues/161

**Comment by balta2ar** [comment]
Are you sure you're using right repository? Shouldn't it be `Plugin 'terryma/vim-multiple-cursors'`?

**Comment by louwers** [comment]
Thank you **balta2ar**.
Coming from Sublime, this was the first plugin I installed. Now I know how to do it correctly.
