### ISSUE TITLE
Could `Multiple_cursors_before/Multiple_cursors_after` be arrays?

### ISSUE THREAD

**Issue by xcodebuild** [terryma/vim-multiple-cursors#172]
I try to make `[fcitx.vim for osx]` work with `vim-multiple-cursors` at https://github.com/CodeFalling/fcitx-vim-osx/commit/3593614364dd7961e1e9cecff301903cf84da00e?diff=split.

But how to avoid conflict with other `Multiple_cursors_before/Multiple_cursors_after`?Could they be arrays?

**Comment by faceleg** [comment]
@eapache @djjcast @balta2ar @aschrab thoughts?

**Comment by balta2ar** [comment]
Do I understand it right that you intend your plugin to be compatible with vim-multiple-cursors out of the box? So you basically want to insert your own hook into `Multiple_cursors_before`?

If so, so far I have witnessed only reversed direction of integration. Meaning that if some plugin wants to be compatible with vim-multiple-plugins, they provide two functions `turn-on` and `turn-off` and ask the user to call these switchers in `Multiple_cursors_before/after`. For example: https://github.com/Valloric/YouCompleteMe/pull/1165. Will that work for you?

**Comment by djjcast** [comment]
The User autocmd event can be used to allow multiple "before" and "after" hooks. One plugin that uses this pattern is [junegunn/goyo.vim](https://github.com/junegunn/goyo.vim). See
* https://github.com/junegunn/goyo.vim#callbacks
* https://github.com/junegunn/goyo.vim/blob/master/autoload/goyo.vim#L272
* https://github.com/junegunn/goyo.vim/blob/master/autoload/goyo.vim#L371
* `:help :doautocmd`

**Comment by CodeFalling** [comment]
@balta2ar Yeah you got it.But I just don't want to trouble users to call them in their `.vimrc`.

**Comment by faceleg** [comment]
@CodeFalling did you get this working?

**Comment by CodeFalling** [comment]
@faceleg No.Still have to trouble users to do something in `.vimrc`.

But `autocmd` may a better idea than `array`.
