### ISSUE TITLE
"call <snr>58_apply_user_input_next" inserted

### ISSUE THREAD

**Issue by dc-psv** [terryma/vim-multiple-cursors#173]
Hi,

I have a little report, I did this:

1. Installed plugin using Vundle.
2. Typed any test text without saving it.
3. Placed cursor to the word and <C-n> on it.
4. Pressed `I` and i have result: "call <SNR>58_apply_user_input_next('i')"

Please see this picture: http://take.ms/9V5qT

Thank you!

**Comment by dc-psv** [comment]
Anyone? Maybe i am doing something wrong.

**Comment by balta2ar** [comment]
`I` is not supported. https://github.com/terryma/vim-multiple-cursors/issues/167#issuecomment-149878012

**Comment by dc-psv** [comment]
@balta2ar, thank you for reply!
