### ISSUE TITLE
hitting save inserts vimscript

### ISSUE THREAD

**Issue by AndrewRayCode** [terryma/vim-multiple-cursors#174]
hitting save (⌘-s) in macvim inserts this:

```
if expand("%") == ""|browse confirm w|else|confirm w|endif
```

with a linebreak at the end, in all places a cursor is

**Comment by faceleg** [comment]
Not for me using nevim - can we have more details please?

**Comment by DelvarWorld** [comment]
https://github.com/DelvarWorld/configs/tree/master/.vim you can my entire vim setup if you want

**Comment by faceleg** [comment]
It's much more helpful if you provide a minimal vimrc that shows the problem.

See: https://github.com/terryma/vim-multiple-cursors/blob/master/ISSUES.md

**Comment by Borissov** [comment]
I override all command keys in MacVim and all work good. But this is not solution.

**Comment by antoinemadec** [comment]
@AndrewRayCode , @borissov do you still see the issue with an up to date version of the plugin ?
If so, could you please:

- provide us with a minimal .vimrc
- provide us with the macvim version that you use
- send use the precise sequence of keys to reproduce the issue

Thanks in advance :)
