### ISSUE TITLE
Configure 

### ISSUE THREAD

**Issue by shiro-saber** [terryma/vim-multiple-cursors#175]
Sorry for this, I'm new in this, how I can configure for ctrl + l start multiple cursors, how I add a new cursor and how I can select some words only in insert mode?

Thanks

**Comment by faceleg** [comment]
If you select something, you can add new cursor with <kbd>C-n</kbd>.  If you select with visual block mode <kbd>S-v</kbd> then press <kbd>C-n</kbd> you will get one cursor per line. 

Other than that, please see the documentation: https://github.com/terryma/vim-multiple-cursors/blob/master/doc/multiple_cursors.txt
