### ISSUE TITLE
Feature request: Press CTRL-j or CTRL-k to add cursor under or over current cursor

### ISSUE THREAD

**Issue by erf** [terryma/vim-multiple-cursors#176]

**Comment by rodfersou** [comment]
I always do the combination of vim commands:
* go to the start block
* press v
* go to the end block
* press ctrl-n

and voilla, the vim visual selection is turned into multiple cursors

**Comment by erf** [comment]
I'm using that as well, but i still like the idea to be able to add a cursor above or below the current line.
