### ISSUE TITLE
Visual select inside with multiple cursors doesn't work

### ISSUE THREAD

**Issue by erf** [terryma/vim-multiple-cursors#177]
If i go to visual block mode, select a 3 lines and and press ctrl-n, i get 3 cursors, but if i then try to visually select the content inside a tag with `vi'`, it doesn't work. I get the message: `Key ' cannot be replayed at 3 cursor locations.`.

Example content:
```
'ab'
'abc'
'abcde'
```

**Comment by rodfersou** [comment]
I'm not sure, but I think this solved for me:

    set selection=inclusive

it is in the FAQ

**Comment by erf** [comment]
It seems to work now..
