### ISSUE TITLE
Support for fanfingtastic

### ISSUE THREAD

**Issue by hallzy** [terryma/vim-multiple-cursors#179]
Would you ever consider having support for fanfingtastic?

ie, if fanfingtastic is enabled, disable it when the start key is pressed, and re-enable fanfingtastic once the multiple cursors have been exited.

By the nature of fanfingtastic, when you do an f F t or T command it carries over to the next line as well. With having multiple cursors, this often messes up the whole text

**Comment by eapache** [comment]
That's relatively easy for us to do as long as fanfingtastic provides a way to enable/disable itself, which as far as I can tell it does not. Once that's done we can add hooks.

**Comment by hallzy** [comment]
See the above referenced issue. It looks like fanfingtastic has just added flag to enable and disable itself with `g:fing_enabled = 1`

**Comment by eapache** [comment]
OK, all you should have to do in your vimrc is define two functions:
```vim
function Multiple_cursors_before()                                               
  " Do the thing to disable fanfingtastic                                     
endfunction                                                                      
                                                                                 
function Multiple_cursors_after()                                                
  " Do the thing to re-enable fanfingtastic
endfunction                                                                      
```

**Comment by hallzy** [comment]
Ah, I had not realized that those existed for me to use! Thanks.

For anyone else interested, I added this to my .vimrc and it all works:

```vim
function Multiple_cursors_before()
  call FanfingTasticDisable()
endfunction

function Multiple_cursors_after()
  call FanfingTasticEnable()
endfunction
```
