### ISSUE TITLE
Can not execute a command in 'command window' by click <CR>

### ISSUE THREAD

**Issue by hiveer** [terryma/vim-multiple-cursors#180]
<img width="588" alt="can not execute" src="https://cloud.githubusercontent.com/assets/3827780/11973524/43eabe00-a996-11e5-80c9-dec0ad91bb71.png">

As the image shows here, when I enter <CR> on `split`, it just select it, not executes it.

**Comment by balta2ar** [comment]
@hiveer What is that supposed to mean? Please elaborate.

**Comment by hiveer** [comment]
@balta2ar In Vim, it will get into **command window**, if I enter any of the commands `q: q? q/`.  Then I can use `j k` to move the cursor to any of the command in history. If I want re-execute one of them, I need to move the cursor to it first, then click <CR>.

But now, after I installed `vim-multiple-cursors`, the click of <CR> didn't work any more. It will not execute the command, but just select it instead.

**Comment by faceleg** [comment]
Can you please provide a minimal .vimrc that replicates this?

**Comment by faceleg** [comment]
https://github.com/terryma/vim-multiple-cursors/blob/master/ISSUES.md
