### ISSUE TITLE
Pressing ESC with multiple cursors in visual mode should not quit cursors

### ISSUE THREAD

**Issue by erf** [terryma/vim-multiple-cursors#186]
Pressing ESC with multiple cursors in visual mode should not 'close' cursors .. but return to normal mode (and keep multiple cursors). Only pressing ESC in normal mode should quit multiple cursors.

**Comment by herrbischoff** [comment]
:+1:

**Comment by rodfersou** [comment]
related to https://github.com/terryma/vim-multiple-cursors/issues/103
please take a look at [this documentation](https://github.com/terryma/vim-multiple-cursors#gmulti_cursor_exit_from_visual_mode-default-1)

can you close this issue for me? I have no permission

**Comment by herrbischoff** [comment]
That's great, thank you very much! :)
