### ISSUE TITLE
Cannot go into insert mode after <C-n>

### ISSUE THREAD

**Issue by Tonkpils** [terryma/vim-multiple-cursors#190]
I'm not sure if this is the desired behavior but doing the following commands on this text

```
foo = ["Hello", "Cool", "Bye"]
```
`0f,v<C-n>i` won't go into insert mode as it used to previously. However, pressing `I` will go to insert mode at the beginning of the word. Also, instead of directly pressing `i`, pressing `v` then `i` will go into insert mode.

**Comment by faceleg** [comment]
This has been discussed before - `i` doesn't work in vim's block selection mode, we have to use `I` instead. This won't be changed.

**Comment by djjcast** [comment]
`i` in multicursor Visual mode now works like `i` in regular Visual mode - see `:help v_i`. To illustrate with the default mappings and above example text, type `0f"v<C-n><C-x><C-n><C-x><Esc>lvi"` - this should visually select the words 'Hello', 'Cool', and 'Bye'.
