### ISSUE TITLE
Clarify issue creation requirements to save contributor time

### ISSUE THREAD

**Issue by faceleg** [terryma/vim-multiple-cursors#192]
@balta2ar @aschrab @eapache I've created this: https://github.com/terryma/vim-multiple-cursors/blob/master/ISSUES.md and updated the readme.

Please feel free to modify it as you see fit. We need people to be more helpful than just providing the bare minimum information when creating issues.

**Comment by eapache** [comment]
If you name it `CONTRIBUTING.md` then github automatically shows it when filing new issues.

**Comment by faceleg** [comment]
Done, thanks for the tip
