### ISSUE TITLE
Random characters are inserted when entering Insert mode via 'a' or 'i'

### ISSUE THREAD

**Issue by HendrikPetertje** [terryma/vim-multiple-cursors#196]
# Expected
when selecting text with v (for visual mode), then l (to select characters to the right), then [ctrl]+n to select next occurrence, then v (to exit visual mode), then i or a (to insert). 
Insert mode should be openend and I should be able to write stuff.

## Instead
When doing the things above and hitting i or a random characters (mostly 0) are added at the cursor.

## Demo
![out](https://cloud.githubusercontent.com/assets/3583395/13317290/e1512882-dbb4-11e5-9722-21faf090c2d6.gif)

# Environment Information
MacOSX el Capitan
---
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 12 2016 10:38:22)
MacOS X (unix) version
Included patches: 1-1301
Compiled by Homebrew
---

# my vimrc

I use the configs from
[dotvim-vimrc](https://github.com/astrails/dotvim/blob/master/vimrc) which load:

- [global.vim](https://github.com/astrails/dotvim/blob/master/global.vim)
- [plugins](https://github.com/astrails/dotvim/blob/master/plugins.vim)
- [macros](https://github.com/astrails/dotvim/blob/master/macros.vim)

my own added applets (runs after plugins.vim):

```
NeoBundle 'jdkanani/vim-material-theme'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'terryma/vim-multiple-cursors'
NeoBundle 'ctrlpvim/ctrlp.vim'
NeoBundle 'vim-airline/vim-airline-themes'
NeoBundle 'rking/ag.vim'
```

My own added config (runs last)
```
syntax enable
set background=dark
colorscheme Tomorrow-Night-Eighties

set autoread

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_quiet_messages = {}
let g:syntastic_ruby_checkers=['rubocop', 'mri']

set colorcolumn=80

set clipboard=unnamed

let NERDSpaceDelims=1

let g:ctrlp_map = '<c-l>'
let g:ctrlp_cmd = 'CtrlP'

map <c-l> :CtrlP <CR>

autocmd BufRead,BufNewFile *.erb set filetype=eruby.html

let g:airline#extensions#tabline#enabled = 1
```

**Comment by HendrikPetertje** [comment]
This error was and is caused by the plugin "autocomplete"
http://www.vim.org/scripts/script.php?script_id=1879

when entering insert mode autocomplete tries to create popups. which fails with the  multiple cursors system this repo uses.

This seems to be a fix for now.

```
function! Multiple_cursors_before()
  AutoComplPopdisable
endfunction

function! Multiple_cursors_after()
  AutoComplPopenable
endfunction
```

I still have some problems executing these commands though. seems they are not recognized (though I 'm having them run last)

**Comment by faceleg** [comment]
Yeah this is the fix for this particular issue, thanks for such an incredibly detailed report!

What did you use to create your amazing gif?
