### ISSUE TITLE
Feature Request: create cursor with vim motion

### ISSUE THREAD

**Issue by cryptobird** [terryma/vim-multiple-cursors#197]
Full integrations with vim motions! If there was a separate shortcut, like <C-m>, you could combine it with a vim motion to create new cursors, for example:
If I have a list of 6 items, I could <C-m>j to spawn a cursor below the single I have already. from there, <C-n> could redo my last <C-m> command, until the end of this multi cursor. then I could <C-m>$ to make new cursors at the end of every line I had a cursor. Support for vim motions could make this phenomenal.
I would try to do this, but I have never written vimscript before and this seems like a difficult way to jump in.

**Comment by mikh3x4** [comment]
I very much want to see this feature developed. I don't have any vim script experience but I'm serious considering learning just to develop this. The regular <CTRL>-n would just be a subset of this using the * motion
