### ISSUE TITLE
Doesn't distinguish between characters and words

### ISSUE THREAD

**Issue by gpalsingh** [terryma/vim-multiple-cursors#198]
In the screenshot the cursors should not have been created at "mm".
![mutliple_cursor_bug](https://cloud.githubusercontent.com/assets/12171804/14062986/d1e1862e-f3da-11e5-8c43-6f158e0895b2.png)

**Comment by faceleg** [comment]
You can skip selections with `c-x`

**Comment by antoinemadec** [comment]
@gpalsingh, this has been fixed a long time ago: ```<C-n>``` selects word without boundaries (like ```*```).
More recently we introduced: ```g<C-n>``` selects word without boundaries (like ```g*```).
