### ISSUE TITLE
Autocompletion is not working propperly

### ISSUE THREAD

**Issue by MaG21** [terryma/vim-multiple-cursors#202]
The auto-completion menu disappears without selecting an option.
The last cursor does not autocomplete properly.

**Comment by naggie** [comment]
Are there an plans to fix this?

**Comment by balta2ar** [comment]
@naggie Not likely. As you can see, this plugin is not actively developed. If you can come up with a patch, you're welcome to do it. Also, this seems to be a duplicate of #144.
