### ISSUE TITLE
<Leader>n will NOT work correctly

### ISSUE THREAD

**Issue by tiagoboldt** [terryma/vim-multiple-cursors#203]
Quoting the docs: 

> IMPORTANT: Please note that currently only single keystrokes and special keys can be mapped. This means that a mapping like <Leader>n will NOT work correctly. For a list of special keys that are supported, see help :key-notation`.

This is an issue for me, since I use the leader key to access most plugins, as well as many other users do (hence already being noted in the docs). I've found some bugs describing the issue, but all where closed. Opening this issue to try to get the discussion back on going.

**Comment by antoinemadec** [comment]
Duplicate, see #226 for more info.
