### ISSUE TITLE
Is it possible to select 200 keywords with several keystrokes

### ISSUE THREAD

**Issue by rbn42** [terryma/vim-multiple-cursors#204]
Could some people tell me if it is possible to select 200 keywords with several keystrokes? I have tried `200<C-n>` which does not work.

Thanks

**Comment by faceleg** [comment]
The only way I know is to press <C-n> 200 times

**Comment by rbn42** [comment]
lol, thanks.

**Comment by balta2ar** [comment]
@rbn42 Hold on a second!

You can use `:MultipleCursorsFind keyword`. I have this binding in my vimrc:
``` vim
nnoremap <silent> <M-j> :MultipleCursorsFind <C-R>/<CR>
vnoremap <silent> <M-j> :MultipleCursorsFind <C-R>/<CR>
```

This allows me to a) search for the keyword using `*` b) turn search results into cursors with `Alt-j`.

**Comment by rbn42** [comment]
Great, that is exactly what I want. Thanks, @balta2ar.

**Comment by faceleg** [comment]
Wow this is such a good solution! I'm putting it in the readme (and into my vimrc)

**Comment by faceleg** [comment]
https://github.com/terryma/vim-multiple-cursors/blob/master/README.md#q-how-can-i-select-n-keywords-with-several-keystrokes-i-have-tried-200c-n-which-does-not-work
