### ISSUE TITLE
Escaping removes original cursor highlight in Gvim

### ISSUE THREAD

**Issue by sourlemon11** [terryma/vim-multiple-cursors#205]
In Gvim, I used ESC to leave the multiple cursors mode, which it did. The ruler shows that the cursor was able to move around. However, the cursor was not highlighted in Gvim. I can reset the cursor by refreshing the file (:e). I tested this issue in terminal vim with no problem whatsoever.

**Comment by unclechu** [comment]
Duplicate of #201

**Comment by antoinemadec** [comment]
Unable to reproduce. Closing issue.
