### ISSUE TITLE
Plugin can not work in some symbols, just like ) (  > ; space

### ISSUE THREAD

**Issue by whcn** [terryma/vim-multiple-cursors#206]
As titled said
![image](https://cloud.githubusercontent.com/assets/15919565/16675935/3d628038-44f8-11e6-828b-d7fa83c45de7.png)

**Comment by balta2ar** [comment]
A part of me wants to say this is by design. @whcn Try entering Visual mode first. Put your cursor on "<", hit `v`, then Ctrl-n.
