### ISSUE TITLE
'i','a','I', 'A' do not work in normal mode.

### ISSUE THREAD

**Issue by tecfu** [terryma/vim-multiple-cursors#209]
**Expected Behavior**

:help vim-multiple-cursors

> After you've marked all your locations with CTRL-N, you can change the visual
> selection with normal Vim motion commands in Visual mode. You could go to
> Normal mode by pressing v and wield your motion commands there. Single key
> command to switch to Insert mode such as `c` or `s` from Visual mode or `i`,
> `a`, `I`, `A` in Normal mode should work without any issues.
> 

**Actual Behavior**

I select multiple matches using C-n, then press v, then pressing A,a,I,i does nothing. 

If this is the wrong usage, it really would be nice to have an example that shows how to append with multiple cursors activated. 

**Environment**

OS: Ubuntu 14.04
Platform: Gnome Terminal -> Vim 8.0, Nvim 0.1.6-dev

**Comment by tecfu** [comment]
This was due to a conflict with the vim-smartpairs plugin.

**Comment by siriniok** [comment]
Seems like I have such conflict with another plugin. How to solve it?
