### ISSUE TITLE
[Feature] Support multikey commands

### ISSUE THREAD

**Issue by terryma** [terryma/vim-multiple-cursors#21]
Currently the plugin doesn't work for multikey commands in any mode once multicursor mode is started. Actions like `ciw` in normal mode causes undetermined behavior since the plugin literally tries to fan out `c`, `i`, and `w` individually at every virtual cursor location. Adding this support requires the plugin to be more intelligent with user input, deciding what to 'keep' vs what to 'fan out'.

**Comment by eapache** [comment]
This is basically already done by the insert_maps and normal_maps. The only thing left is visual_maps (ticket #111) and then setting some sane defaults for these options.

My .vimrc currently contains the following, which I suggest as a good starting point for defaults.

```
let g:multi_cursor_insert_maps={'\':1}
let g:multi_cursor_normal_maps={'c':1, 'd':1, 'r':1, '=':1, '<':1, '>':1}
```

**Comment by roryokane** [comment]
There are a lot of multi-key built-in mappings that are missing from your suggested `multi_cursor_normal_maps`. I think this is a complete list:

```vim
let g:multi_cursor_normal_maps={'!':1, '@':1, '=':1, 'q':1, 'r':1, 't':1, 'T':1, 'y':1, '[':1, ']':1, '\\':1, 'd':1, 'f':1, 'F':1, 'g':1, '"':1, 'z':1, 'c':1, 'm':1, '<':1, '>':1}
```

I identified these multi-key mappings by going across the keyboard, row by row, and checking whether that key, or Shift plus that key, was a multi-key mapping by default.

**Comment by faceleg** [comment]
@roryokane do you want to submit a PR with this change, assuming it won't break anything?
