### ISSUE TITLE
"No more matches" on single special characters

### ISSUE THREAD

**Issue by QuentinFresnel** [terryma/vim-multiple-cursors#210]
I can't use multiple cursors on single special characters like ".
Thus, the 3rd example "Do it backwards too! This is not just a replay of the above gif :)" on main page does not work for me. This error is displayed:

> No more matches

I don't have the error for single letters. 

OS : ubuntu 14.04
VIM - Vi IMproved 8.0
iterm, remote ssh

[my .vimrc](https://github.com/terryma/vim-multiple-cursors/files/513385/vimrc.txt)

edit: I reproduced the bug on 
mac os x 
VIM - Vi IMproved 8.0 (installed with homebrew)
iterm, local file

**Comment by tbertelsen** [comment]
Same issue here, though also for more than one special character.

In the "Do it backwards example" the first C-n selects the comma and surrounding quotes (which is unexpected). The second press fails with "No more matches", even though the quote-comma-quote string exists several times on the line.

**Comment by hems** [comment]
same here

**Comment by hems** [comment]
@tbertelsen / @QuentinFresnel Unfortunately i'm a noob on vim scripting, but investigating the code brought me to this function: https://github.com/terryma/vim-multiple-cursors/blob/master/autoload/multiple_cursors.vim#L806-L817 ... hopefully anyone with more experience on vim scripting could have a proper look?

````s:use_word_boundary```` <~ is also a suspect in this investigation.

🕵️🕵️🕵️

**Comment by jszroberto** [comment]
same here. I was trying to follow the examples and came across the same

**Comment by eapache** [comment]
That sounds fine to me, but I think that existed before I started playing with this repo.
