### ISSUE TITLE
When I installed the plugin, the arrow keys failed!

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [terryma/vim-multiple-cursors#213]
Hello!
    I have disabled all other plugins and leave only multiple-cursors. When I press the arrow keys appear, the following problems.
![Uploading image.png…]()

OS:Ubuntu 14.04
vim:7.4

**Comment by louwers** [comment]
https://github.com/terryma/vim-multiple-cursors/blob/master/CONTRIBUTING.md

**Comment by antoinemadec** [comment]
Not able to reproduce. Closing issue.
