### ISSUE TITLE
Enter key is always mapped

### ISSUE THREAD

**Issue by vatrat** [terryma/vim-multiple-cursors#215]
This could very well be my own fault, but I can't figure out how to get this to stop.
OS: Fedora 25
Neovim version: 0.1.7
Expected behavior: <enter> key is not mapped by this plugin
Actual behavior: <enter> is mapped in modes x and n to act the same way as next

Relevant section of init.vim:
```
call plug#begin('~/.config/nvim/plugged')
" ...
Plug 'terryma/vim-multiple-cursors'
" ...
call plug#end()
" ...
" Vim-multiple-cursors mappings
let g:multi_cursor_use_default_mapping=0
let g:multi_cursor_next_key    = '<C-m>'
let g:multi_cursor_prev_key    = '<C-l>'
let g:multi_cursor_skip_key    = '<C-M>'
let g:multi_cursor_quit_key    = '<Esc>'
```

Adding
```
nunmap <enter>
xunmap <enter>
```
after this config does not work, and tells me upon sourcing my init.vim that the mappings do not exist. However, if I do :verbose map <enter> after vim has already started, it shows that vim-multiple cursors mapped <enter>. If I nunmap and xunmap <enter> after neovim has already sourced my init.vim, it works. So, it seems that either something happens after init.vim has already been loaded or I don't understand the order in which things are run.

Asciinema:
Explanation, example:
https://asciinema.org/a/49cetu1j3l3h6waonrrgay4pj
What happens when I load neovim with the unmaps:
https://asciinema.org/a/7m640hd6ucvatrssnvu90zp81

Now, I opened the file from which neovim claims enter was mapped:
https://asciinema.org/a/2fh7jog0teny0x0lvcqayit7h

Sorry about the confusing presentation.
Note: You may have seen, in the last asciinema, the "multiedit" folder next to "vim-multiedit-cursors". This is only there because vim-plug hasn't deleted it. Multiedit is not referenced my init.vim.

**Comment by ijse** [comment]
Hope this being fixed cause it does affect the <enter> key in quickfix list using.

**Comment by dcyriller** [comment]
I got the exact same issue when mapping <C-m> like this:
`let g:multi_cursor_next_key = '<C-m>'`

When mapping `g:multi_cursor_next_key` to something else, the issue disappear.

**Comment by antoinemadec** [comment]
@dcyriller @vatrat ```<C-m>``` and ```<enter>``` code for the same key in both Vim and Neovim.

@dcyriller , if you use the follwing in your ```init.vim```:
```vim
let g:multi_cursor_next_key = '<C-n>'
nunmap <C-n>
xunmap <C-n>
```
you will observe the same behavior. This is not specific to ```<enter>```

@vatrat , @ijse, so if I understand correctly, the issue you have is that ```unmap``` does not work like you expect because it seems **vim-multiple-cursors** maps the ```multi_curso_*_key``` after ```unmap```.
Is that correct ?
What I don't understand is why you want to ```unmap <enter>``` and do ```let g:multi_cursor_next_key = '<C-m>'``` at the same time ? (once again ```<C-m>``` and ```<enter>``` are identical)

Once you respond to those questions, I will try to look into it.
Thanks in advance :)

**Comment by antoinemadec** [comment]
@dcyriller @vatrat @ijse do you have any news about that ?
I will close this issue in one week if I don't get any response.
Thanks in advance :smile:

**Comment by antoinemadec** [comment]
No response in 2 weeks: closing the issue.
Please reopen if need but don't forget to respond to my questions.

**Comment by backslash112** [comment]
Got the same problem here!
macOS 10.13.4 (17E199)

**Comment by antoinemadec** [comment]
@backslash112 ```<C-m>``` and ```<enter>``` code for the same key in both Vim and Neovim.
If you still think there is an issue in this plugin, please elaborate and respond to those questions:
https://github.com/terryma/vim-multiple-cursors/issues/215#issuecomment-378375548
