### ISSUE TITLE
work not correctly with neocomplete

### ISSUE THREAD

**Issue by jinleileiking** [terryma/vim-multiple-cursors#216]

**Comment by balta2ar** [comment]
@jinleileiking Could you please be more specific?

**Comment by jinleileiking** [comment]
1. enable neocomplete
2. select multi words using ^N
3. `c`to change sometest
4. type some char, then neocomplete completing , shows `<Plug>Neo....`

**Comment by balta2ar** [comment]
Why's nobody reading the README?..

https://github.com/terryma/vim-multiple-cursors/issues/214
https://github.com/terryma/vim-multiple-cursors#interactions-with-other-plugins

**Comment by jinleileiking** [comment]
sorry :(
