### ISSUE TITLE
Feture request: add autocmd User Multiple_cursors_before and Multiple_cursors_after 

### ISSUE THREAD

**Issue by roxma** [terryma/vim-multiple-cursors#218]
Hi, I've received several issues about being incompatible with vim-multiple-cursors on [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager/issues/18), and another plugin [vim-paste-easy](https://github.com/roxma/vim-paste-easy/issues/4)

Although this  can be easilly fixed by adding `Multiple_cursors_after` and `Multiple_cursors_before` into user's vimrc, I think it would be nice to have  `autocmd User Multiple_cursors_before` and `autocmd User Multiple_cursors_after`. With this I can simply add `autocmd User Multiple_cursors_before`  into both plugins. Then a user may not need to know about how to resolve the conflict manually.

Thoughts?

**Comment by roxma** [comment]
It should be helpful for auto completion plugin users. By the way, I've also seen simillar reports on [deoplete](https://github.com/Shougo/deoplete.nvim/issues/162)  @Shougo

**Comment by balta2ar** [comment]
@roxma Unfortunately, this is not a very actively developed project. You can summon contributors who contributed last commits here, like @eapache and @djjcast, though. Of course, feel free to send a PR.

**Comment by eapache** [comment]
tbh it's been a while and it's not super-clear to me what the advantage of an autocmd is over a function like we already have? Is it just more idiomatic? I currently have the following in my `.vimrc`:
```vim
function Multiple_cursors_before()
  let s:old_ycm_whitelist = g:ycm_filetype_whitelist
  let g:ycm_filetype_whitelist = {}
endfunction

function Multiple_cursors_after()
  let g:ycm_filetype_whitelist = s:old_ycm_whitelist
endfunction
```
How would that convert to autocmds?

**Comment by roxma** [comment]
@eapache 

I'm not suggesting to remove the existing `Multiple_cursors_before` function.

Without autocmd, you're forcing a user to know about how to fix the conflict, then put some code into user's vimrc, otherwise it will break things.

With autocmd, it's more extensible, because other plugins having conflicts may register a hook like this `au User Multiple_cursors_before call completion_lock()`,  `au User Multiple_cursors_after call completion_unlock()`, if the plugin maintainer wants to. In this case, a user will never need to know how to fix it because it just works.

As a plugin maintainer, I would like to add sane default to fix conflicts for existing popular plugins, like vim-multiple-cursors. But I can't achieve that without autocmd.
