### ISSUE TITLE
<SNR>145_apply_user_input_next('i'), <SNR>139_apply_user_input_next('i')

### ISSUE THREAD

**Issue by D1mon** [terryma/vim-multiple-cursors#224]
select `<img>` tag by pressing `<C-n>`, then Shift+a (A) and then Space.
[See video](https://www.dropbox.com/s/r1l3rvp4ns8eoop/vim-multiple-cursors%20%28bug%29.mkv?dl=0).
The error occurs in all insertion modes (I, A, c).
Do not work (a, i).

The error occurred due to a space.
Does not work only in html files

neovim 0.2.0

**Comment by antoinemadec** [comment]
@D1mon could you please try on an up-to-date version of vim-multiple-cursors and tell us if the bug is still present?
If it is still present, could you please share your ```.vimrc``` with us?

Thanks in advance :)

**Comment by D1mon** [comment]
This error is not available right now.
