### ISSUE TITLE
It's slow in neovim, but fast in vim. Does anyone have the same problem?

### ISSUE THREAD

**Issue by iuunhao** [terryma/vim-multiple-cursors#225]
It's slow in neovim, but fast in vim. Does anyone have the same problem?

**Comment by DeathRay1977** [comment]
Yes!

**Comment by eapache** [comment]
It is reasonably fast for me on both by default.

**Comment by tuyenpm9** [comment]
vim profile so significant change when has no multiple-cursor:
`506.000  260.000: VimEnter autocommands`

down to 178 when no multiple-cursor.
`421.000  178.000: VimEnter autocommands`

that's a lot of changes in speed.

**Comment by crisidev** [comment]
I use neovim and it is pretty slow. I haven't tried with vim.

**Comment by perrupa** [comment]
This plugin was unusably slow until I realized I had another plugin writing the buffer with every change (`907th/vim-auto-save`). Rather than bother with setting up a throttle limit, I just disabled that plugin, which made this crazy-fast again.

**Comment by Leandros** [comment]
Thanks for the tip, @perrupa. Turns out that YankRing.vim slows down vim-multiple-cursors 😐 
Now is the question, whether this can be fixed, and what the culprit could be?

**Comment by antoinemadec** [comment]
@iuunhao @perrupa @Leandros : do you still see any speed issue on neovim ?
If so could you please provide us with the minimal ```.vimrc``` to repoduce ?
Otherwise, I will close the issue.

**Comment by perrupa** [comment]
I believe my slowness was caused by another plugin saving files when entering/exiting insert mode. The `Plug_` issue has long since been resolved for me.

Huge thanks for the amazing plugin and all the work to fix these issues! 👍

**Comment by antoinemadec** [comment]
Thanks for the feedback! Closing the issue.
Poke me if you want to reopen it.
