### ISSUE TITLE
changing words without deleting them first?

### ISSUE THREAD

**Issue by hems** [terryma/vim-multiple-cursors#227]
On ST you would be able to select the words with cmd + d, and then change them without having to delete them, for instance just writing at the end of it.

On vim i'm trying to achieve the same behaviour, but unfortunately as i do ctrl-n and then press "c" the words get erased and i have to type all the characters again.

is there a way around it?

**Comment by balta2ar** [comment]
Press "v" after ctrl-n, then press "a".

**Comment by hems** [comment]
@balta2ar that's absolutely perfect, thanks!!!

the only issue i'm having now is trying to map "kj" to exit instead of <Esc> but having

````
let g:multi_cursor_quit_key='kj'
````

isn't working. sorry as you can see i'm still grasping some of the black magic on vim.
