### ISSUE TITLE
Is there a way to silence no matching autocommands

### ISSUE THREAD

**Issue by ndaljr** [terryma/vim-multiple-cursors#233]
I've been using Ale for my linting and I've noticed in some scenarios when there's an error in the status bar it conflicts with this plugin causing this to occur. I would just like to silence the message when I quit the multi select

![image](https://user-images.githubusercontent.com/18214059/34261612-5c50a7e6-e672-11e7-9dc4-417dfccf6141.png)

**Comment by ndaljr** [comment]
Found out that you can remap the quit keys and you can add silent call infront of it like this `nnoremap <silent><C-h> :call multiple_cursors#quit()<CR>`. Closing this

**Comment by ndaljr** [comment]
Edit. I just realised calling the next command for finding the next match __ALWAYS__ causes a no matching statement. How do i get this to be silent?

**Comment by tomspeak** [comment]
@terryma I am also getting this issue when I am done editing and press `<Esc>` to exit. 

`No matching autocommands` appears below.

What information do you need to help debug this?

**Comment by balta2ar** [comment]
@tomspeak For the most part it's not just information that we need, it's enthusiastic contributors that we need. @terryma does not seem to maintain this repo anymore. I guess you could try contacting latest contributors to this repo, but as you can see there is not much activity going on here.
