### ISSUE TITLE
conflict with fcitx

### ISSUE THREAD

**Issue by rinetd** [terryma/vim-multiple-cursors#244]
when enable fcitx pulgin       ` Plug  'h-youhei/vim-fcitx'`
vim-multiple-cursors will be work error

**Comment by antoinemadec** [comment]
@rinetd could you please provide us with:

1. a minimal ```.vimrc```
2. the steps to repoduce the bug
3. the error message or bad behavior we are supposed to see

Without that, we won't be able to help you.
Thanks in advance :)

Antoine

**Comment by antoinemadec** [comment]
Step to reproduce the bug on Ubuntu:

1. install fcitx: ```sudo apt install fcitx```
2. use the following .vimrc:

```vim
call plug#begin('~/.vim/plugins_by_vimplug')
Plug '/home/amadec/source/vim-multiple-cursors'
Plug 'h-youhei/vim-fcitx'
call plug#end()

set nocompatible               " get rid of vi compatibility
```

Any PR or workaround is welcome.

**Comment by rinetd** [comment]
if i enable  Plug 'h-youhei/vim-fcitx'
vim-multiple-cursors will not work 

```
Plug 'terryma/vim-multiple-cursors'
Plug 'h-youhei/vim-fcitx'
let g:multi_cursor_use_default_mapping=0
let g:multi_cursor_start_word_key='<C-n>'
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'

```
```
call plug#begin('~/.vim/bundle')

let g:plug_threads = 8
let g:plug_timeout = 3600

for files in s:plug_files
  for f in split(glob(s:vim_home.files), "\n")
    exec "source ".f
  endfor
endfor
call plug#end()

set nocompatible  
```

**Comment by rinetd** [comment]
aftet enbale fctix 
when i select multi words  and then press s key
this section will be insert:
`<Plug>(multiple-cursors-input)lug>(multiple-cursors-apply) `

**Comment by V2X2M** [comment]
> aftet enbale fctix
> when i select multi words and then press s key
> this section will be insert:
> `<Plug>(multiple-cursors-input)lug>(multiple-cursors-apply) `

The function of s key is delete current char and insert.
