### ISSUE TITLE
Multiple cursor not working when selecting last match on the same line.

### ISSUE THREAD

**Issue by mboughaba** [terryma/vim-multiple-cursors#245]
Hello,

I love this plugin and I've been using it since forever. Thanks for putting it all together, it saves me so much time and makes me look cool when doing live coding :heart: 

I noticed a small bug which I believe was introduced after the big change that we got maybe few weeks ago (not sure 100%).

I am on the latest version of vim-multiple-cursors.
The bug occurs only when there are matches on the same line and when selecting the last match of the line first. Check the live reproducer below.

![multiple_cursor_backward_selection_bug](https://user-images.githubusercontent.com/3800584/36640432-c534c1a4-1a1e-11e8-97d5-cfcf27cafbad.gif)

Any hint where to start to make a fix would be welcome.

Cheers,
Mo

**Comment by balta2ar** [comment]
cc @antoinemadec

**Comment by antoinemadec** [comment]
Will take a look at it next week (my dog ate my laptop power supply...). Im pretty sure that my commit introduced that regression indeed.

Thanks for the feedback 😉

**Comment by antoinemadec** [comment]
Surprisingly, this regression was already present before my commits.
For instance this commit is also failing:
a97dab5bc440bf0a7b62bb2de4479963a888f4ff
For info, v2.0 was not working either...

@mboughaba are you sure this has ever worked ?
If so, could you please provide use with:

1. a minimal .vimrc
2. the last commit at which this feature was working

For 2., you can use ```git bisect```:
  https://git-scm.com/docs/git-bisect

Thanks in advance,
Antoine

**Comment by mboughaba** [comment]
@antoinemadec 
I couldn't find a version where this was working, maybe this is not a regression.

I am trying to find a fix.
given the string below on line 1:
```vim
test test test
```
1. on `<c-n>` selection from the beginning of the line, the cursor list will contain:
```
[ [1, 1], [1, 4] ]
[ [1, 2], [1, 5] ]
[ [1, 3], [1, 6] ]
```

2. on `<c-n>` selection from the end of the line, the cursor list will contain:
```
[ [1, 11], [1, 14] ]
[ [1, -3], [1, 0] ]
[ [1, 2], [1, 5] ]
```
error will be raised when processing user input:
![image](https://user-images.githubusercontent.com/3800584/37029245-07f0d28e-2137-11e8-93d7-7592227abb30.png)

`[[1, 11], [1, 14]]` is wrong because it doesn't take into account the line length after starting change on selected cursors.
`[1, -3], [1, 0]` is wrong calculation, maybe because of the same reason above.
`[1, 2], [1, 5]` is correct.

**Comment by antoinemadec** [comment]
@mboughaba got it.
That would be absolutely fantastic if you could come up with a pull request!

Let us know if you have any questions :)
