### ISSUE TITLE
Not working with lexima.vim

### ISSUE THREAD

**Issue by romgrk** [terryma/vim-multiple-cursors#248]
Version: `NVIM v0.2.3-533-g9a36337d3` (neovim)

Whenever I enter insert mode and use any [lexima.vim](https://github.com/cohama/lexima.vim) mappings, the plugin fails and leave the options in a broken state (messes `'clipboard'`, etc.).

Steps:
 - Enter multiple_cursor mode
 - Press `i`, then `<esc>`

![screenshot from 2018-03-05 15-38-30](https://user-images.githubusercontent.com/1423607/36998613-7f25b56a-208b-11e8-9db0-81c047e257ba.png)

**Comment by balta2ar** [comment]
I think you could try combining this (https://github.com/terryma/vim-multiple-cursors#interactions-with-other-plugins) and this (https://github.com/cohama/lexima.vim/blob/master/doc/lexima.txt#L202).

**Comment by romgrk** [comment]
Ye, not the expected behavior. Do you think it's feasable to make this work with other plugins?

Also linking this, as it's a very similar issue: https://github.com/justinmk/vim-sneak/issues/151

**Comment by balta2ar** [comment]
Sorry, I don't know the internals well enough to reason about this... Maybe @antoinemadec has any ideas?

**Comment by antoinemadec** [comment]
@romgrk I was not able to reproduce your issue.
Could you please provide us with a **minimal** .vimrc reproducing this error ?
