### ISSUE TITLE
multiple_cursors.vim#L1229 should check for expr mapping

### ISSUE THREAD

**Issue by char101** [terryma/vim-multiple-cursors#249]
Hi,

I have this mapping in my vimrc

```viml
inoremap <expr> <Esc>      pumvisible() ? "\<C-e>" : "\<Esc>"
```

That causes this error if I press `Esc` when running multiple cursors

```
Error detected while processing function <SNR>84_wait_for_user_input:
line   47:
E15: Invalid expression: "pumvisible() ? "\\<C-E>" : "\\<Esc>""
```

So I think [multiple_cursors.vim#L1229](https://github.com/terryma/vim-multiple-cursors/blob/master/autoload/multiple_cursors.vim#L1229) should check for `expr` mapping (using `dict` parameter of `maparg`) and remap without enclosing quotes if it is an expr mapping in [multiple_cursors.vim#L1233](https://github.com/terryma/vim-multiple-cursors/blob/master/autoload/multiple_cursors.vim#L1233).

Thanks.

**Comment by char101** [comment]
I don't quite understand what the code does but remapping it without the quotes prints `\<Esc>` instead.

**Comment by antoinemadec** [comment]
@Char101, you are absolutely right.
I just fixed it and read your comment afterwards: that is exactly what I did :)

#250 fixes the issue.
Thanks for the feedback!
