### ISSUE TITLE
Change flow for checks

### ISSUE THREAD

**Issue by antoinemadec** [terryma/vim-multiple-cursors#253]
vimrunner is the solution that we use today to run our checks when a new commit is pushed.
The issue is that it uses vim client-server feature.

And it seems that the characters pushed by vim clients can sometimes be delayed until vim has nothing to do anymore. Which is a big problem for the mappings since we use while loops waiting for characters that are blocking the client's chars from being consumed...

My question is this one: could we use something like expect instead ?
If so, who would be confortable enough to implement this new flow ?

TODO: reintroduce insert mapping test when that will be done

**Comment by antoinemadec** [comment]
@eapache @balta2ar what do you guys think ?

**Comment by eapache** [comment]
I'm not sure what you're thinking of exactly. AFAIK there is no way for a script to "yield" to vim while waiting for a character.

**Comment by antoinemadec** [comment]
#252 reintroduced the "sleep" command for mappings and special keys completion, masking this issue.
It is only triggered when CPU usage is 100%, which should never happen anyway.
Bottom line: no need to change the flow for checks.
