### ISSUE TITLE
Debug left on inside master.

### ISSUE THREAD

**Issue by kennyle1412** [terryma/vim-multiple-cursors#259]
I map jk as my ESC sequence. Pressing j to exit insert mode these statements keep popping up. I think they're debug statements that were left inside the release? Deleting or commenting out would be appreciated since I don't want to keep doing that every update.

https://github.com/terryma/vim-multiple-cursors/blob/995b52f9aaf3ffa48150f9a279e438a19e7fcf5c/autoload/multiple_cursors.vim#L1261

![out](https://user-images.githubusercontent.com/10459400/38450904-91141bb2-39eb-11e8-8da5-e3edf1a88395.gif)

**Comment by antoinemadec** [comment]
@kennyle1412 , that is a debug message indeed, and was left there unintentionally.
It has been fixed in e1b7471 thanks for the feedback :)
