### ISSUE TITLE
Cursors created from Vertical Block Selection are misaligned

### ISSUE THREAD

**Issue by balta2ar** [terryma/vim-multiple-cursors#260]
Consider the following file:
```
8	2018.8.txt
9	2018.9.txt
10	2018.10.txt
11	2018.11.txt
```
It contains Tab characters after the first column of numbers. When I create a vertical block anywhere after tabs and create multiple cursors from it, those cursors that are on 10 or below are misaligned:
![multiple-cursors-vertical-block-with-tabs](https://user-images.githubusercontent.com/340676/38454950-62885cca-3a79-11e8-9f60-0244cda54fd9.gif)
Key sequence on the demo:
```
e
<C-v>jjj
<C-n>
```

**Comment by antoinemadec** [comment]
I was able to reproduce the issue (using ```setlocal shiftwidth=4 tabstop=4```).
The issue is that, ```in multiple_cursors#new()```, the following line:
https://github.com/terryma/vim-multiple-cursors/blob/e1b7471d282a7c6804b2f5ee596638f821b8b6c5/autoload/multiple_cursors.vim#L148
calls ```s:cm.add(pos)``` with the wrong ```pos```:
```
[1, 6]
[2, 6]
[3, 6]
[4, 6]
```
instead of:
```
[1, 6]
[2, 6]
[3, 7]
[4, 7]
```

If you're not convinced that **7** is the right column value for the last 2 cursors, try ```:echo getpos('.')``` on those.

@balta2ar could you maybe try to create a PR ?

**Comment by balta2ar** [comment]
@antoinemadec I'm not sure I'm following... How do we determine correct `pos` on each line during the iteration? What I have in mind is actually moving the cursor from top to bottom (`j`) and calling `getpos('.')` on each line. Any other ideas?

**Comment by antoinemadec** [comment]
Nope, i dont have a clue. Maybe other plugin had to face the same issue ? In that case it might be good to get inspired by the solution they found. But the ```j``` solution sounds reasonable to me.

**Comment by antoinemadec** [comment]
@balta2ar , any news about this ?

**Comment by balta2ar** [comment]
I remember about this one, but I think I'll be able to attack it not sooner than the end of May... So feel free to provide a solution earlier, if you have one.
