### ISSUE TITLE
Is vim-multiple-cursors making nerdtree slow?

### ISSUE THREAD

**Issue by cdata** [terryma/vim-multiple-cursors#262]
I just updated my local vim plugins on two computers, and noticed that expanding folders in nerdtree became rather slow. I used process of elimination, adding in my plugins one at a time to see if any one plugin was the culprit. I discovered that the slowness occurs as soon as I enable vim-multiple-cursors (even when no other plugins are enabled).

I've been a long time user of this plugin (I would almost say I can't live without it 😍). So, my intuition is that a very recent change introduced this issue.

Here is a screen recording of the normal folder expansion speed:

![fast-nerdtree](https://user-images.githubusercontent.com/240083/38461568-e7c01626-3a88-11e8-9fd2-ed8e6a73f304.gif)

And here it is with the latest vim-multiple-cursors enabled:

![slow-nerdtree](https://user-images.githubusercontent.com/240083/38461573-f6e821fc-3a88-11e8-9eae-61be81bc2703.gif)

It seems like there is now a couple of hundred milliseconds delay that wasn't there before when expanding and collapsing folders.

One note that may be relevant: I tested opening / closing folders with mouse interaction, and that seems to be fine. Only keyboard interaction seems to be slow.

**Comment by antoinemadec** [comment]
I have 2 questions for you:
1- did you change vim-multiple-cursors default mappings ?
2- in NerdTree you press enter to open those folders right ?

**Comment by cdata** [comment]
1: Nope, using the defaults
2: Yes, I'm pressing enter

**Comment by antoinemadec** [comment]
Ok thanks. Its because of the new ```<C-m><C-n>``` mapping.
```<C-m>``` and enter are the same keys in Vim.
I will fix that tomorrow, thanks again for the feedback !

**Comment by antoinemadec** [comment]
Fixed by f019fcd , we now use ```<A-n>``` to select all occurrences instead of ```<C-m><C-n>```.

I did not update the doc with the new mapping yet since we are working on a refactoring of the doc #258 
But I will do it afterwards.

**Comment by dsifford** [comment]
@antoinemadec You are wonderful, thanks for the quick fix :+1: :pray:
