### ISSUE TITLE
seems to freeze when going to insert mode

### ISSUE THREAD

**Issue by 1ak31sha** [terryma/vim-multiple-cursors#263]
i use <C-n> to select a few lines, then press i to insert at all those locations, but it seems to freeze, i tried pressing all buttons, i have to quit the terminal. Am i doing it right? - maybe im missing the key to press?

macOS 10.13.3
neovim 0.2.2

**Comment by antoinemadec** [comment]
Could not reproduce the issue.
Could you please provide us with:

- the minimal ```init.vim``` to reproduce the bug
- the keys to press to reproduce the bug

Thanks in advance!

**Comment by 1ak31sha** [comment]
i tested this minimal init.vim (ran :PlugClean too):
`call plug#begin('~/.config/nvim/plugged')
  Plug 'terryma/vim-multiple-cursors'
call plug#end()`

i was still able to get the error. it seems to happen more on larger files(250 lines) or when many cursors are created, such as around 10. keys to press:

- esc
- v
- l (move one space to highlight a pattern)
- <C-n> * 10 
- i . it freezes here

**Comment by antoinemadec** [comment]
You never press ```<C-n>``` ?

**Comment by 1ak31sha** [comment]
yes i press C-n 10 times

**Comment by antoinemadec** [comment]
@1ak31sha I was still not able to reproduce.
My setup:

- NVIM v0.2.2
- test file: [foo.txt](https://github.com/terryma/vim-multiple-cursors/files/1891000/foo.txt)
- minimal vimrc: [vimrc.txt](https://github.com/terryma/vim-multiple-cursors/files/1891003/vimrc.txt)

Btw, please note that -after pressing ```<C-n>``` a couple of times- ```i``` won't go to insert mode, but ```I``` will.  
Indeed, when invoking *vim-multiple-cursors* by selecting a pattern, you switch to Visual mode, not Normal mode. You can refer to the README or the vim help ```:help vim-multiple-cursors```

If that did not fix your issue and you think there is a real bug, please:

- make sure to be up to date
- provide me with the exact **file** and the exact **pattern** that trigger the bug

Thanks in advance :smile:

**Comment by 1ak31sha** [comment]
shift-i seems to be working!! thanks so much!!!

**Comment by rickdps** [comment]
Thank you 1ak31sha. I am having the same problem and your workaround worked.

**Comment by mfiano** [comment]
I also have this problem, and while Shift-I does work, but if I accidentally press `i` vim freezes completely and I must close my terminal. For that reason I cannot use this plugin with the risk of losing work in any unsaved buffers when I must kill the terminal to recover. A minimal recipe is:

`<A-n>`
`i`
(vim is not completely frozen).

**Comment by wallysslima** [comment]
Vim freezes completely when I press `i`, something to prevent this?

**Comment by tbhockey** [comment]
I have the same problem described by @mfiano should this issue not be reopened? I cannot use this plug with the risk pressing `i` causes.

**Comment by antoinemadec** [comment]
@tbhockey no need to reopen this. I updated the FAQ:
https://github.com/terryma/vim-multiple-cursors#faq

Just pressing ```shit-i``` after you pressed ```i```, exactly like in **visual** mode.
That should do it.

**Comment by tbhockey** [comment]
That definitely clears things up, thanks!

**Comment by gcorrel** [comment]
NJ ice tips from you guys here. However, my issue right about now is when I press <shift-9> (for an opening bracket/parentheses "(" ), vim freezes completely, which closing my terminal would only be an alternative solution to continue my work but by doing so, I often loose a lot of work. Any ideas please?

**Comment by gcorrel** [comment]
Nice tips from you guys here. However, my issue right about now is when I press (for an opening bracket/parentheses "(" ), vim freezes completely, which closing my terminal would only be an alternative solution to continue my work but by doing so, I often loose a lot of work. Any ideas please?

**Comment by Qizot** [comment]
If somebody happen to have frozen vim (I use neovim but I guess it's the same kind of bug) you can press <C-c> and it should unfreeze, you may be left with bugged highlight but then just press <C-n><Esc> and you are good.
