### ISSUE TITLE
README still refers to <C-m><C-n> keybinding for select_all

### ISSUE THREAD

**Issue by uri** [terryma/vim-multiple-cursors#264]
f019fcd0d8c5d8a6c3a5993e476ce3be420cdc6e

https://github.com/terryma/vim-multiple-cursors/blob/f019fcd0d8c5d8a6c3a5993e476ce3be420cdc6e/README.md#mapping

**Comment by balta2ar** [comment]
https://github.com/terryma/vim-multiple-cursors/issues/262#issuecomment-379579253

**Comment by antoinemadec** [comment]
Fixed.
