### ISSUE TITLE
<A-n> does not work on Vim CLI

### ISSUE THREAD

**Issue by antoinemadec** [terryma/vim-multiple-cursors#265]
@balta2ar @eapache , I added ```<A-n>``` to the default mappings to select all occurrences of a pattern.

The issue is that ```<A-letter>``` mappings are not working on Vim in a terminal, because Vim expect 8bit keys formatted in a certain way, and VTE does not implement it yet. This is a well known issue:
https://bugzilla.gnome.org/show_bug.cgi?id=31316#c35

Point is, we should use a mapping that:
- work for anyone out of the box
- does not interfere with other mappings

So do you have any suggestion?

**Comment by antoinemadec** [comment]
Here are some suggestions:

1. map *select all* on ```<C-b><C-n>```
2. map *select all* on ```<leader><C-n>```
3. map *select all* on ```<leader>n```
4. keep *select all* on ```<A-n>``` and add a note in README and vim help
5. do not map *select all* and add a note in README and vim help

Personally, I like 2. 3. and 5.

**Comment by balta2ar** [comment]
I like 5. We already have an example for `<A-j>`. On top of that, the more default mappings we have, the more it's likely that the user will have a conflict. Also, I'd check whether there is default mapping for a similar action in other editors.

**Comment by antoinemadec** [comment]
Or, we could leave the mappings as is, and add the following in the FAQ:
**Q** ```<A-n>``` is not working
**A** on certain terminals, ```<A-n>``` is interpreted as ```<esc>n```, here is a workaround to add in your ```.vimrc```:
```vim
" fix alt+n mapping in Vim CLI
if !has('gui_running')
  exec "map \en <A-n>"
endif
```

What do you think ?

**Comment by azamat-sharapov** [comment]
@antoinemadec above workaround didn't work for me. 
Terminal: Konsole, on Ubuntu 16.04, using tmux.

**Comment by balta2ar** [comment]
Maybe a link to discussions about why Alt cannot be mapped in vim could also be useful.
I don't have a strong opinion about that, though. In my case, `<A-n>` is already taken by another command so I'm remapping back to `<C-m><C-n>` anyway.

**Comment by antoinemadec** [comment]
@balta2ar good call regarding the link.
Regarding ```<C-m><C-n>``` please note that ```<C-m>``` and ```enter``` are the same keys in vim.
Meaning that all the normal mappings using ```enter``` will take ```timeoutlen``` to complete.
This is why I decided to use ```<A-n>``` instead.

@azamat-sharapov I tried Konsole+Ubuntu+tmux and the mapping worked properly when adding the code in my previous command.
I will add something in the vimrc and README soon about that.
In the mean time, you can try that (make sure to replace the string):
```vim
map "in Insert mode, type Ctrl+v Alt+n here" <A-n>
```

**Comment by antoinemadec** [comment]
FAQ regarding this issue added in README and vim-help.
