### ISSUE TITLE
Is it possible to reselect all previously selected text items?

### ISSUE THREAD

**Issue by ashishtibrewal** [terryma/vim-multiple-cursors#267]
Hi all,

I was wondering if it is possible to reselect all previously selected text items (i.e. something similar to Vim's inbuilt `gv`)? Currently, using `gv` selects only the last selected text.

Any solutions/help would be much appreciated. Thanks. :)

**Comment by balta2ar** [comment]
Could you provide an example usecase for that?

**Comment by ashishtibrewal** [comment]
If you select all occurrences of a variable (say `str` is the variable name) within a function/scope using ctrl-n, and then change it to `fleStr`. But after the change I realize that I've made a typo (I instead wanted it to be `fileStr`) and want to reselect all the items from my last selection and correct the typo, I can't do that. I have to go back to the top and reselect every occurrence manually. This can be time consuming if there are a lot of occurrences of the variable. I know that there is alt-a to select all occurrences but that doesn't limit the scope. It selects all occurrences across the entire file.

**Comment by balta2ar** [comment]
Sounds like a plausible usecase. I wonder if there is anything similar in other editors/plugins?
