### ISSUE TITLE
<SID>AutoPairsReturn displays in file when typing newline

### ISSUE THREAD

**Issue by hallzy** [terryma/vim-multiple-cursors#268]
Hi, I am having a rather similar issue to #246 again using the same minimal vimrc as in that issue. The commit after the one that fixed my problem in #246 seems to have reintroduced at least part of the problem I was previously having (specifically, commit 1bb3a2209ef684588a4dd74fd25b3aac078ee074).

For reference, the minimalist vimrc being used is:

```vim
call plug#begin()

Plug 'terryma/vim-multiple-cursors'
Plug 'jiangmiao/auto-pairs'

call plug#end()

set nocompatible

set timeoutlen=3

let g:multi_cursor_exit_from_visual_mode=0
let g:multi_cursor_exit_from_insert_mode=0
```

With the above minimalist vimrc file, if I select something with multiple cursors, and then I want a newline vim prints out `<SID>AutoPairsReturn` to the screen.

A specific example is if I start with this text:

```
x,x,x,x
```

I create multiple cursors on each of the commas, then I press `c<cr>` to change the commas to newlines, this is the resulting file:

```
x
<SID>AutoPairsReturnx
<SID>AutoPairsReturnx
<SID>AutoPairsReturnx
```

But I would expect:

```
x
x
x
x
```

I have only had this issue with the `AutoPairsReturn` this time though, and it worked fine in the commit previous to 1bb3a2209ef684588a4dd74fd25b3aac078ee074.

**Comment by antoinemadec** [comment]
@hallzy thanks a lot for the precise feedback, this is much appreciated.
Problem has been solved :smile:
