### ISSUE TITLE
"No more matches" on single special characters

### ISSUE THREAD

**Issue by kfir-rocketrip** [terryma/vim-multiple-cursors#269]
For this text trying to find and replace the char `-` give you "No more matches" after the first selection

```
one - four three
three - four one
four ten seven - three
```

macOS 10.13.4 (17E202)
Vim version 8.0.1806
vim-multiple-cursors version 2.2

**Comment by antoinemadec** [comment]
@kfir-rocketrip thanks for the feedback, but this behavior is expected:

- ```<C-n>``` behaves like when you search with ```*```, i.e.: **with word boundaries**
- ```g<C-n>``` behaves like when you search with ```g*```, i.e.: **without word boundaries**

You can refer to our README.md, ```:help g*``` or ```:help multiple-cursors-usage```

Bottom line: ```g<C-n>``` will work on charaters like ```-```, you can also use the selection mode like so: ```<C-v><C-n>```

Cheers,
Antoine
