### ISSUE TITLE
Pressing Ctrl-C with multiple cursors selected leaves editor in weird state

### ISSUE THREAD

**Issue by d11wtq** [terryma/vim-multiple-cursors#27]
Firstly, massive kudos for bringing this project to Vim. I'm hoping to help and contribute when I get time, but until then I'll file some issues just so they are recorded and somebody else may be able to fix them.

If you select multiple cursors, then press Ctrl-C, you'd expect the cursors to go away, much like pressing ESC. This is what happens when you are in visual mode and you press Ctrl-C. Instead, with multiple cursors what happens is all the cursors remain marked, even though they're not really active anymore. Pressing ESC at this point does nothing, and the only way to clear them is to do: Ctrl-n, ESC.

**Comment by tony** [comment]
This is an issue that is getting in my way.  I don't understand the inner technicalities, but:

I use ``<ctrl-c>`` as a way to get out of insert mode. Frankly, I'd like it to be a way to get out of any special mode. 

I also see this was filed as an "enhancement". While this may or may not require refactoring, it does run contrary to the behavior that an end-user would expect.

Would it help if the function to quit out of highlighting was made public? I tried giving it a shot in https://github.com/terryma/vim-multiple-cursors/pull/126.

**Comment by faceleg** [comment]
While the PR you submitted does seem to let me quit multi cursor mode with `<C-c>`, it leaves the editor with the previous selection still visible

**Comment by tony** [comment]
I also notice this same problem.  The behavior in my PR is flawed and it should probably be reverted.  I have tried various approaches but could not find a way to clear previous selections.

**Comment by faceleg** [comment]
In vanilla, how does `esc` trigger the desired behaviour?

**Comment by axs221** [comment]
This seems to work for me:

> let g:multi_cursor_quit_key='<C-c>'
> nnoremap <C-c> :call multiple_cursors#quit()<CR>

As found on the README, on the bottom of this section:

https://github.com/terryma/vim-multiple-cursors#mapping

**Comment by Aadniz** [comment]
~~`multiple_cursors#quit()` doesn't appear to be a callable function~~ My bad, wrong git page
