### ISSUE TITLE
Feature request: Expose underlying functionality

### ISSUE THREAD

**Issue by leotaku** [terryma/vim-multiple-cursors#270]
I think exposing some of the underlying functionality of `vim-multiple-cursors` via global functions could be very helpful. 

Currently (I think) we can only really place cursors in a number of predefined ways. Manly I would like to see the ability to create cursors at arbitrary positions using global functions. Also accessing and moving different cursors individually seems like a good idea, but is probably too ambitious.

The motivation for doing this (IMO) would be to improve `vim-multiple-cursor`'s usefulness in different workflows and maybe aid integration with other plugins. This is just a simple idea I had when using this plugin for a couple of hours, suggestions and additions are highly welcome.

**Comment by antoinemadec** [comment]
@LeOtaku that sounds like a good idea.
We are running short on contributors, could you please create a pull request ?
