### ISSUE TITLE
Pressing "i"

### ISSUE THREAD

**Issue by babakness** [terryma/vim-multiple-cursors#272]
Hey guys, I'm just getting into vim and I'm really liking the plugin but I have just one issue--I know when I press `ctrl-n` I can then type 'v' then `i` to enter insert mode. The things is, if I forget to press `v` and just press `i`, it seems like vim just hangs and become complete unresponsive, not sure how to get out of it.

What is `ctrl-n i` anyway? Can it somehow be mapped to just do what I expected or at least not hang?

**Comment by babakness** [comment]
Okay, I figured it out just after asking, strange I was stuck on a while.

Anyone who finds this, if you just press `i` before pressing `v` you are buffering input values until you press `shift-i`. Not sure what mode this is but that's what get you out.

Perhaps there is an even more enlightened feedback?

**Comment by antoinemadec** [comment]
Yes this is normal. When pressing ctrl-n you enter visual mode.
You can read the README or the vim :help if it is still not clear ;)

**Comment by Memorytoco** [comment]
That's really helpful . Thanks.

**Comment by antoinemadec** [comment]
For info, I add this question in the FAQ: https://github.com/terryma/vim-multiple-cursors#faq
Cheers!
