### ISSUE TITLE
[question] press ':' cause lag in normal mode

### ISSUE THREAD

**Issue by pingsoli** [terryma/vim-multiple-cursors#273]
I check the key mappings.

`:verbose map :`
the output as the following:
```
x  :<C-U>call  * multiple_cursors#select_all("v", 0)<CR>                            
        Last set from ~/.vim/bundle/vim-multiple-cursors/plugin/multiple_cursors.vim
n  :call       * multiple_cursors#select_all("n", 1)<CR>                            
        Last set from ~/.vim/bundle/vim-multiple-cursors/plugin/multiple_cursors.vim
```

I  press the `:` in normal mode, vim will match the key mappings.
I want to remove the key mappings in normal mode, what should I do ?

**Comment by pingsoli** [comment]
I check the `plugin/multiple_cursors.vim` file, and found this.

```
" External mappings                                            
if exists('g:multi_cursor_start_key')                          
  exec 'nnoremap <silent> '.g:multi_cursor_start_key.          
        \' :call multiple_cursors#new("n", 0)<CR>'             
  exec 'xnoremap <silent> '.g:multi_cursor_start_key.          
        \' :<C-u>call multiple_cursors#new("v", 0)<CR>'        
endif                                                          
                                                               
if exists('g:multi_cursor_start_word_key')                     
  exec 'nnoremap <silent> '.g:multi_cursor_start_word_key.     
        \' :call multiple_cursors#new("n", 1)<CR>'             
  " In Visual mode word boundary is not used                   
  exec 'xnoremap <silent> '.g:multi_cursor_start_word_key.     
        \' :<C-u>call multiple_cursors#new("v", 0)<CR>'        
endif                                                          
                                                               
if exists('g:multi_cursor_select_all_key')                     
  exec 'nnoremap <silent> '.g:multi_cursor_select_all_key.     
        \' :call multiple_cursors#select_all("n", 0)<CR>'      
  exec 'xnoremap <silent> '.g:multi_cursor_select_all_key.     
        \' :<C-u>call multiple_cursors#select_all("v", 0)<CR>' 
endif                                                          
                                                               
if exists('g:multi_cursor_select_all_word_key')                
  exec 'nnoremap <silent> '.g:multi_cursor_select_all_word_key.
        \' :call multiple_cursors#select_all("n", 1)<CR>'      
  " In Visual mode word boundary is not used                   
  exec 'xnoremap <silent> '.g:multi_cursor_select_all_word_key.
        \' :<C-u>call multiple_cursors#select_all("v", 0)<CR>' 
endif                                                          
```

I really not want these external mappings, any idea to solve this ?

**Comment by antoinemadec** [comment]
@pingsoli ```:``` is not mapped by default, all the ```g:multi_cursors_*``` are mapped to ```:*```, but ```:``` itself is not mapped to anything.

When I do ```:verbose map :``` I get ```No mapping found``` as you should too.

Could you please share:

- your OS
- your version of Vim (or Neovim)
- the **minimal** ```.vimrc``` to reproduce this issue

Thanks in advance :smile:

**Comment by pingsoli** [comment]
@antoinemadec , Happy wedding.

**Comment by pingsoli** [comment]
@antoinemadec , I remove the following mappings from my vimrc, it works fine.
```
let g:multi_cursor_select_all_word_key = ''
let g:multi_cursor_select_all_key      = ''
```

`<alt>` is not work in vim, so I decide to unmap these keys. It's really a bad idea.

**Comment by pingsoli** [comment]
At last, I remap these keys.
```
let g:multi_cursor_select_all_word_key = '<C-m>' 
let g:multi_cursor_select_all_key      = 'g<C-m>'
```
I love multiple-cursors. thanks for your reply.

**Comment by antoinemadec** [comment]
@pingsoli to make ```<A-n>``` working, you can look at the FAQ:
https://github.com/terryma/vim-multiple-cursors#faq

**I strongly recommend not using ```<C-m>``` as this combination is equivalent to ```<enter>``` for Vim!!!**

**Comment by pingsoli** [comment]
@antoinemadec 
Thank you so much. I have tried some ways, but not work.

I ssh to ubuntu on my windows laptop. `<alt>` key has other mappings in windows, so, the situation gets complicated. I think, maybe I can adapt for without `<alt>` key in vim.

Fortunately, I rarely use `<c-m>` in normal mode.

I really appreciate your reply. Thank you sooooooo much.
: )
