### ISSUE TITLE
Problems trying to follow examples

### ISSUE THREAD

**Issue by SirWindfield** [terryma/vim-multiple-cursors#276]
I was trying out example Nr.2 and noticed that I can't move the cursor to the end of line after typing `"`. The example states that I should press <C-e> to move to the end of line, but it just kind of glitches and creates duplicated letters at the cursors position. I am not sure if they changed the shortcut or it isn't available anymore.

**Comment by SirWindfield** [comment]
The sequence you described works perfectly. I forgot to add a link to the one that I meant. In the [wiki](https://github.com/terryma/vim-multiple-cursors/wiki/Keystrokes-for-example-gifs), there is an entry describing each example and their keystrokes. `<C-e>` is used to jump to the end of the file. But that doesn't work for me. I'm not sure if this is a normal vim command or maybe some other plugin.

**Comment by antoinemadec** [comment]
```<Ctrl-e>``` was not working for me either.
I changed the doc accordingly.

Please close this ticket if this fixed your issue.

**Comment by antoinemadec** [comment]
@SirWindfield do you have any news about that?
Is the new Tiwki example working better now?

**Comment by SirWindfield** [comment]
Ye, works perfectly now :) thanks !
