### ISSUE TITLE
Compatibility issue with vim-autoclose

### ISSUE THREAD

**Issue by andyearnshaw** [terryma/vim-multiple-cursors#281]
After making edits using multiple cursors, I cannot exit insert mode.  I have narrowed the issue down to having both vim-multiple-cursors and https://github.com/townk/vim-autoclose installed.  Here's the minimum `.vimrc`:

```
call plug#begin('~/.config/nvim/plugged')
Plug 'terryma/vim-multiple-cursors'
Plug 'townk/vim-autoclose'
call plug#end()
```

Here's the error message that I get when exiting insert mode:

> ^[' cannot be replayed at 2 cursor locations

I'm sure this used to work (I have used both plugins for a few years and only got this error after setting up a new machine) and vim-autoclose has not had any updates for many years, so I think something must have changed in vim-multiple-cursors to introduce this conflict.

I'm using NVIM v0.3.1.

**Comment by artanikin** [comment]
Try this https://github.com/mg979/vim-visual-multi/wiki

**Comment by andyearnshaw** [comment]
I switched from *vim-autoclose* to *vim-autopairs* and that seems to be a better plugin for that anyway.  Nevertheless, *vim-visual-multi* looks to be more powerful than *vim-multiple-cursors*, so I've switched to that too.
