### ISSUE TITLE
Delay exiting "insert mode"

### ISSUE THREAD

**Issue by sblask** [terryma/vim-multiple-cursors#282]
I recently updated my version of Multiple Cursors and now I get a delay before exiting "insert mode"(ctrl-n, make a change and then exit). I traced this back to #252 where the plugin started to use timeoutlen. Now I like to have timeoutlen set to `0` so I can exit the normal insert mode immediately. However, to not break the leader key in other modes I use the following:

```
    autocmd InsertEnter  *                 set timeoutlen=0
    autocmd InsertLeave  *                 set timeoutlen=1000
```

This works great for everything but Multiple Cursors (since #252). I tried to use MultipleCursorsPre and MultipleCursorsPost in the same way as the above autocommands, but either I do it wrong, or it doesn't work. Is there any way to fix this?

**Comment by antoinemadec** [comment]
@eapache can you please help @sblask regarding the usage of ```MultipleCursorsPre``` and ```MultipleCursorsPre```?

If not, who is the right person?

**Comment by eapache** [comment]
`MultipleCursorsPre` and `MultiplerCursorsPost` are not mode-specific so I think this question was just mixing those up. Unfortunately I can't think of an obvious solution to this problem off the top of my head.
