### ISSUE TITLE
<c-m> mapping throws off the plugin start

### ISSUE THREAD

**Issue by hrai** [terryma/vim-multiple-cursors#283]
Using this mapping sets the `<CR>` to start selecting the word under cursor.

I'm using vim 8.x on Ubuntu

Mapping values:
```

let g:multi_cursor_use_default_mapping=0

" Default mapping
let g:multi_cursor_start_word_key      = '<C-m>'
let g:multi_cursor_next_key            = '<C-m>'
```

**Comment by antoinemadec** [comment]
Hi @hrai , this is true, but has nothing to do with our plugin.
As far as Vim is concerned, ```<C-m>``` and ```<CR>``` are the same thing.

I hope this helps!

**Comment by hrai** [comment]
I had no idea. Thanks for that info 😃
