### ISSUE TITLE
set "let g:multi_cursor_select_all_word_key = '<C-m>'" but <CR> also

### ISSUE THREAD

**Issue by changlianxiya139** [terryma/vim-multiple-cursors#284]
.vimrc
let g:multi_cursor_select_all_word_key = '\<C-m\>'

normal mode press \<CR\> Can also be
multi cursor select all word
How to disable \<CR\> key to "multi cursor select all word"?

**Comment by antoinemadec** [comment]
This has nothing to do with this plugin.
As far as Vim is concerned, ```<C-m>``` and ```<CR>``` are the same thing.

I hope this helps!
