### ISSUE TITLE
exiting insert mode also exits multiple cursor mode

### ISSUE THREAD

**Issue by alexberian** [terryma/vim-multiple-cursors#286]
When inserting text in multiple cursor mode, if i stop inserting, I go back to single cursor mode. I's like to be able to insert in multiple places, as that is one of the main reasons to bother with multiple cursors as opposed to <C-v>

**Comment by antoinemadec** [comment]
As per the README and the vim help:
```
g:multi_cursor_exit_from_visual_mode (Default: 1)

If set to 0, then pressing g:multi_cursor_quit_key in Visual mode will not quit and delete all existing cursors.
Useful if you want to go back to Normal mode, and still be able to operate on all the cursors.

g:multi_cursor_exit_from_insert_mode (Default: 1)

If set to 0, then pressing g:multi_cursor_quit_key in Insert mode will not quit and delete all existing cursors.
Useful if you want to go back to Normal mode, and still be able to operate on all the cursors.
```
Please set both of those settings to 0 in your .vimrc:
```vim
let g:multi_cursor_exit_from_insert_mode = 0
let g:multi_cursor_exit_from_visual_mode = 0
```
But I must say I am not a huge fan of the default to 1.
@eapache do you think we could change those 2 settings to 0 by default?
It feels like more people want to have those set to 0, don't you think?

Thanks,
Antoine

**Comment by eapache** [comment]
Makes sense to me.

**Comment by marcospb19** [comment]
+1
The default should be 1 for both settings :thinking:.

**Comment by alexberian** [comment]
Marcospd19, do yo mean it should be 0?

**Comment by marcospb19** [comment]
Yes, sorry, i edited it.

**Comment by antoinemadec** [comment]
@marcospb19 @alexberian , could you please create a Pull Request?
I am swamped with work right now.

Please make sure to update the **multiple_cursors.txt**, **README.md** and **spec** accordingly.
To run the tests:
```bash
cd vim-multiple-cursors/spec/
bundle exec rake
```

Cheers,
Antoine

**Comment by kinowarrior** [comment]
Wow, this was just what I was looking for.

You should also redo the examples and animated gifs using the new defaults too. It is far more efficient working in normal mode with navigation, rather than using arrow keys in insert mode.

Thanks for the awesome plugin.

**Comment by antoinemadec** [comment]
@marcospb19 @alexberian @kinowarrior a pull request is still welcome :smile:

**Comment by antoinemadec** [comment]
Closing since the feature was implemented.
Thanks again @marcospb19 !

**Comment by andys8** [comment]
So changing the default will now confuse everybody who is used to the behavior ;)

**Comment by marcospb19** [comment]
This is inevitable, and very common to any project, otherwise how are we supposed to improve?

Now you need to press ESC two times, isn't that bad... And also you got a new feature, exiting insert/visual mode without losing the multiple cursors and having to re-select everything

It's worth it

**Comment by andys8** [comment]
Yeah, no troubles. I'll configure the previous behaviour. 

It took me some time to figure out, it's not my typing, it's not my mechanical keyboard's escape key, and it's not a big that will be fixed in the future.

I don't know how changes like this a propagated in the ecosystem of vim plugins. But maybe we can make this change more public by adding it to the README if necessary?

**Comment by andys8** [comment]
Yeah, no troubles. I'll configure the previous behaviour. 

It took me some time to figure out, it's not my typing, it's not my mechanical keyboard's escape key, and it's not a big that will be fixed in the future.

I don't know how changes like this a propagated in the ecosystem of vim plugins. But maybe we can make this change more public by adding it to the README if necessary?

**Comment by antoinemadec** [comment]
The has already been updated.
Also, the name of the commit changing this behavior is very explicit.

Cheers,
Antoine 🐜 1
