### ISSUE TITLE
Input ignored after leading key of insert mode mapping

### ISSUE THREAD

**Issue by tmandry** [terryma/vim-multiple-cursors#289]
If I type the first key of an insert mode mapping (but _not_ the full mapping), the key and some keys after it will be ignored.

~In my experience, this makes it impossible to type the key that starts an insert mode mapping.~ The key can only be typed by typing it and waiting for a few seconds; otherwise, it and the keys typed after it will be ignored.

Here's a spec which fails and the corresponding diff:

```ruby
  specify "#unused mapping" do
    before <<-EOF
      hello world!
      hello world!
      bla bla bla
      bla bla bla
    EOF

    type 'w<C-n><C-n>chey joseph blah blah blah<Esc>'

    after <<-EOF
      hello hey joseph blah blah blah!
      hello hey joseph blah blah blah!
      bla bla bla
      bla bla bla
    EOF
  end
```

```diff
@@ -1,5 +1,5 @@
-hello hey joseph blah blah blah!
-hello hey joseph blah blah blah!
+hello hey eph blah blah blah!
+hello hey eph blah blah blah!
 bla bla bla
 bla bla bla
```

**Comment by antoinemadec** [comment]
@tmandry thanks for the very solid contribution (fix + test).
This is much appreciated!

Feel free to add more features/PR if you feel like it :smile: 

Cheers,
Antoine
