### ISSUE TITLE
Support not moving cursors when scrolling

### ISSUE THREAD

**Issue by tmandry** [terryma/vim-multiple-cursors#291]
Sometimes when I have multiple cursors off-screen and am about to make a change, I want to scroll to see all my cursors again before I make the change.

The problem is, as cursors scroll off the screen they are moved.

In multiple cursor mode I can't see a reason for this behavior. Is it possible to disable this?

**Comment by antoinemadec** [comment]
To be honest, I don't now if this is possible.
I don't have time to work on this plugin anymore, but I will gladly test your PR if you want to submit one.

Thanks,
Antoine
