### ISSUE TITLE
ReadMe have a complex explanation on the usage, bad for newcomers. 

### ISSUE THREAD

**Issue by marcospb19** [terryma/vim-multiple-cursors#292]
At ReadMe:

> select all: <A-n> start muticursor and directly select all matches

I searched for an hour and did not found what `<A-n>` combination actually means, can you edit the text in a way that is friendly to new users of vim? I do know what <C-n> is but some people might not and this is bad for the project in general.

**Comment by antoinemadec** [comment]
@marcospb19 , sorry but ```<A-n>``` is standard way to note ```Alt + n``` in vim.
You try typing the following in vim to get more info:
```vim
:help <A-n
```

Thanks,
Antoine

**Comment by marcospb19** [comment]
This should not be closed, there's no explanation to newcomers of what <C and <A means and we did not discussed it properly, this is not only about me (i expect lots of sublime users to use your software because it's explicitly associated with it).

Seems like urxvt don't support `Alt + N` combination, so i spent most of my time confused, i tried `Alt + N` several times and i only understood the real problem after your explanation, thank you anyways.

**Comment by kinowarrior** [comment]
Hi, could you please elaborate on the line:

`df[$r,0f,v<C-n>…<C-n>c<CR><Up><Del><Right><Right><Right><Del>`

I am unclear what `<Up>` means? I know what it does from the animated gif, I just don't understand which keybinding it is.

All the commands work, just don't understand how you got the cursor to shift upwards one line and then move to the right as a block (prior to the delete backwards part).

Apologies in advance if I missed the obvious.

**Comment by kinowarrior** [comment]
Doh, all working. Deleted question ;(
You help suggestion was spot on.
