### ISSUE TITLE
After enter multi-select and c,  cmd+v does not work

### ISSUE THREAD

**Issue by xlpiao** [terryma/vim-multiple-cursors#293]
After enter multi-select and c,  cmd+v does not work. cmd+v pastes last selected text, but cmd+v does not work after latest update. Anyone meet this issue ?

**Comment by antoinemadec** [comment]
Could you please provide:

- the minimal ```vimrc``` to reproduce the issue
- the steps to reproduce the bug (```cmd``` is not a key)

Thanks,
Antoine

**Comment by antoinemadec** [comment]
@xlpiao , do you have any news about this?
If not, I will close this ticket in 2 weeks.
