### ISSUE TITLE
Request: When in wait_for_user_input(), show prompt

### ISSUE THREAD

**Issue by jamespharvey20** [terryma/vim-multiple-cursors#294]
After the user calls a multiple_cursors function that calls `wait_for_user_input()`, I think it would be useful to to show a prompt in the status line.  Even if it defaulted to off and required an option to turn it on.  Something maybe like "multiple_cursors: "  Ideally, it might even show the mode being `MULTIPLE` instead of `NORMAL`, but I'm not sure vim allows that customization.

Additionally, I think it would be great if vim-multiple-cursors worked together with [vim-airline](https://github.com/vim-airline/vim-airline) so when it's in `wait_for_user_input()`, vim-airline can show mode `MULTIPLE` (or `M` when that plugin is configured to show short mode names), and then nothing would be needed on a second status line when that plugin is being used, because the vim-multiple-cursors mode would be shown on it instead of `NORMAL`.

Assuming you guys might need to work together a small bit, not for the vim-multiple-cursors status line output of course, but for any vim-airline integration, I opened an [issue in vim-airline](https://github.com/vim-airline/vim-airline/issues/1932).

**Comment by chrisbra** [comment]
vim-airline maintainer here: So how would it be possible to detect, whether Vim is in "Multiple Cursor Mode"?

**Comment by antoinemadec** [comment]
@jamespharvey20 @chrisbra , this feature would be good to have indeed.
We need to expose the mode ```vim-multipile-cursors``` is into (```MULTIPLE_INSERT```, ```MULTIPLE_NORMAL```, ```MULTIPLE_VISUAL```).

I don't have much time on my hand right now.
@terryma @eapache @balta2ar @marcospb19 , feel free to create a PR if you feel like it!

Cheers,
Antoine

**Comment by acheronfail** [comment]
I have the same request, however I'm using https://github.com/itchyny/lightline.vim instead.
As long as `vim-multiple-cursors` exposes a way to do this, it should be easy to connect it to lightline too.

**Comment by antoinemadec** [comment]
@acheronfail , correct, once the vim-multiple-cursors mode is accessible, any plugin could benefit from it.
However, I still don't have much time on my hand, sorry...
Pull request welcome! :smiley:

**Comment by chrisbra** [comment]
Why was this closed?

**Comment by balta2ar** [comment]
@chrisbra https://github.com/terryma/vim-multiple-cursors/issues/314
