### ISSUE TITLE
How can I use <A-n> in mac? There is no 'A' key.

### ISSUE THREAD

**Issue by feedliu** [terryma/vim-multiple-cursors#297]

**Comment by antoinemadec** [comment]
Hi @feedliu , this question is larger than this plugin.
Please try resources like stackoverflow to find an answer:
https://stackoverflow.com/questions/7501092/can-i-map-alt-key-in-vim

Then, just modify **vim-multiple-cursors** mappings to your liking:
https://github.com/terryma/vim-multiple-cursors/#mapping

I hope this helps!
Antoine
