### ISSUE TITLE
How to yank multiple cursors?

### ISSUE THREAD

**Issue by eduardoarandah** [terryma/vim-multiple-cursors#298]
I want to copy all classes inside an html document. 

```html
  <div class="page-header__crisis-line--mobile d-block d-lg-none">
    <a href="#" class="text-white">
   something
    </a>
  </div>

  <div class="container">
    <div class="d-flex flex-nowrap justify-content-between align-items-center py-2">

```

I create multiple cursors for `class=` and then `yi"`

but the yank doesn't work.
 
Is there a way of doing it?

**Comment by antoinemadec** [comment]
@eduardoarandah , I tried it and it worked just fine.
Here is what I did:
```vim
" cursor on class
<c-n>
<c-n>
<c-n>
<c-n>
<esc> " to go from visual to normal mode
" move cursors inside double quote
yi"
P
<esc> " to exit multiple-cursors
```

Please reopen with a **minimal vimrc** and a precise **testcase** if it still does not work for you.
Also, please make sure to use an up-to-date version of the plugin.

I hope this help!

**Comment by eduardoarandah** [comment]
Oh, I get it... the yank and paste work when in "multiple-cursors" mode
but it wont work if I press ESC and paste in a stylesheet. 

Example: 
```
(cursor on class)
<c-n>
<c-n>
<c-n>
<c-n>
<esc> (to go from visual to normal mode)
(move cursors inside double quote)
yi"
<esc> (exit multiple cursors)
G  (go to end of file, or another buffer)
p  (this paste won't work)
```
I also tried to do yank-append to register a with 

```
"Ayi" (yank inside " append to register a)
"ap (paste register a)
```
