### ISSUE TITLE
can't return to regular vim and it stucks

### ISSUE THREAD

**Issue by NewUserHa** [terryma/vim-multiple-cursors#299]
`c-n` `c-n` `c-n` `i`
then stacks. even inputting `:`, the cursor at the left bottom just flash once then nothing, of course, `ESC` not working, all key not working.   but sometimes it can return back to regular vim with some random text(maybe the input during stuck).

**Comment by antoinemadec** [comment]
See README: https://github.com/terryma/vim-multiple-cursors#quick-start

> You can now change the virtual cursors + selection with visual mode commands. For instance: c, s, I, A work without any issues. You could also go to normal mode by pressing v and use normal commands there.

After ```c-n``` you are in **visual** mode, meaning that **i** won't behave like in **insert** mode.
Please try capital **I** instead.

**Comment by NewUserHa** [comment]
after pressing `v`, nothing changed.
gvim 8.1.1
win10

**Comment by antoinemadec** [comment]
Please provide a **minimal vimrc** and clear instructions to reproduce this issue.

**Comment by NewUserHa** [comment]
```
set langmenu=none
call plug#begin('$VIM/vimfiles/plugged')

Plug 'terryma/vim-multiple-cursors'

call plug#end()

set encoding=utf-8
```

```
`c-n` `c-n` `c-n` `i' `v`
```
then no key can exit multicursors mode.

**Comment by antoinemadec** [comment]
Please try capital I instead of i.

**Comment by NewUserHa** [comment]
I meant `if input i, it will be stuck, not I. and it's not documented`. did you mean 'input i is wrong'?
