### ISSUE TITLE
Doesn't work with nondefault langmap

### ISSUE THREAD

**Issue by booglewoogle** [terryma/vim-multiple-cursors#300]
Hey,

trying to use this with a nondefault langmap leads to unexpected behaviour. 
e.g. I'm using
`set langmap = kf,KF,ö0,Ö0,ok,OH,ih,IK,ej,EL,al,AJ,hw,HW,ub,UB,xe,XE,üm,ÜM,ya,YA,ä$,Ä$,gg,GG,pu,PU,do,DO,si,SI,lt,LT,rs,RS,mc,MC,td,TD,cy,CY,fn,FN,np,NP,br,BR,wx,WX`
and whatever I bind the commands to on the user-level (the way it's suggested in the readme), the behaviour stays the same. 

I'm thinking maybe somewhere in the definition of the commands the default langmap is assumed? Maybe some sort of mapping is happening somewhere there?

Would be nice if this could be factored out into the user-level mappings maybe. I'd like getting into this. :)

Cheers

**Comment by roket1428** [comment]
It doesn't work in my config file with `langmap` neither.

**Comment by antoinemadec** [comment]
@booglewoogle @roket1428 , I haven't had much time lately, but feel free to create a PR and I will review it :smiley: 
Cheers,
Antoine

**Comment by roket1428** [comment]
> @booglewoogle @roket1428 , I haven't had much time lately, but feel free to create a PR and I will review it smiley
> Cheers,
> Antoine

I don't know vim scripting well to create (or edit in my case) a plugin but I would try to find `normal` keywords which does not include `!` at the end. Would it be enough?
