### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Cvar1984** [terryma/vim-multiple-cursors#303]
I stuck can't escape or doing anything when using visual mode

NVIM v0.4.2                                                                                          Build type: MinSizeRel
Lua 5.3
Compilation: /home/builder/.termux-build/_cache/android-r20-api-24-v2/bin/clang -fstack-protector-strong -Oz -fno-addrsig --target=aarch64-linux-android24 -I/data/data/com.termux/files/usr/include -Os -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/builder/.termux-build/neovim/build/config -I/home/builder/.termux-build/neovim/src/src -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/neovim/build/src/nvim/auto -I/home/builder/.termux-build/neovim/build/include
Compiled by builder@cirrus-ci-task-6281865553510400                                                  
Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"

Run :checkhealth for more info

**Comment by tbhockey** [comment]
+1

**Comment by Cvar1984** [comment]
> +1

No i can't do it anything

**Comment by tbhockey** [comment]
@Cvar1984 probably the same issue as https://github.com/terryma/vim-multiple-cursors/issues/263#issuecomment-523858480

**Comment by antoinemadec** [comment]
@tbhockey can you please provide us with:

- the **minimal** vimrc to reproduce this issue
- the **exact and minimal** set of keys/commands triggering the issue

Thanks,
Antoine

**Comment by tbhockey** [comment]
@antoinemadec it appears this issue has been well-documented in various other issues https://github.com/terryma/vim-multiple-cursors/issues/285. Unless i'm misunderstanding we're all describing the same situation.

**Comment by antoinemadec** [comment]
@tbhockey when using ```ctrl-n``` from **nomal mode**, you will start cursors in **visual mode**.
When typing ``i``, you will have the same behavior as if you were typing ``i`` in **visual mode**.

I tested the following both on the lastest Vim compiled from source and nvim v0.3.8

Minimal **vimrc**:
```vim
call plug#begin('~/.vim/plugins_by_vimplug')
Plug 'terryma/vim-multiple-cursors'
call plug#end()
set nocompatible
```
Scenario described in the issues you mentioned:

- normal mode in a file
- ```ctrl-n``` on a word multiple times
- ```i```, does not seem to respond (**which is the same behavior as in the regular visual mode**)
- **to _fix_ this**, you can press ```I``` or ```ctrl-c```

I just added documentation about this in the **FAQ**, both in the README and the vim help.

If you think there is still a bug, please send us both the minimal vimrc and the exact scenario.
For now, I will close the ticket, feel free to reopen it.

I hope this helps,
Antoine
