### ISSUE TITLE
Crash on search a char using `f` when target char isn't found

### ISSUE THREAD

**Issue by Faham** [terryma/vim-multiple-cursors#304]
To reproduce
Create a file with the following content
```
this is a test
this is a test
this is a test
```
Then create a multi cursor on the three lines and press `f` (to search for a char in line) and then press a char that doesn't exists in the line like `x`. This leads to a whole hang of vim 8.1 and no way to recover from.

**Comment by antoinemadec** [comment]
@Faham thanks for reporting this bug. It also happen on neovim.
The way to workaround this is to press ```CTRL-C```.

If you really want this to be properly fixed, any pull request is welcome.

Thanks,
Antoine
