### ISSUE TITLE
Select all occurrences within specified text area

### ISSUE THREAD

**Issue by DomKennedy** [terryma/vim-multiple-cursors#308]
I'd like to be able to use the `select_all` command within a restricted area, rather than the entire buffer. Ideally this area could be specified as an arbitrary text area.

This would work great for things like renaming an argument to a function, without affecting other variables of the same name elsewhere in the file, but also without manually iterating over every occurrence.

**Comment by antoinemadec** [comment]
@DomKennedy , sorry we don't want to implement this.
Alternatively, you can select your function lines and then run the following command:

`:'<,'>s/old_arg/new_arg/gc`
