### ISSUE TITLE
Multicursor crash when try to insert 

### ISSUE THREAD

**Issue by espilonlola** [terryma/vim-multiple-cursors#313]
Hi,

Frist thanks for this "must have" plugin !
I experiment a crash after trying to enter `insert mode` after getting multi cursors
same issue in **vim** and **neovim**
any clue ?
thanks

**Comment by antoinemadec** [comment]
To enter insert mode from visual mode, you have to press ```I```, not ```i```.
Please try again and let me know if it fixed it for you.

Also, you can consider using this other plugin instead: https://github.com/mg979/vim-visual-multi
It is more actively maintained.
