### ISSUE TITLE
Moving cursors beyond the bounds of a line adds a change to the undo history

### ISSUE THREAD

**Issue by d11wtq** [terryma/vim-multiple-cursors#36]
Minor:

```
a
ab
abc
```

Select the following lines visually, then move right twice, or left once. A change will be added to the undo history for no apparent reason.

`ggVjj<C-n>h<ESC>`

**Comment by ninrod** [comment]
Yes. I came across this while working on another bug. 
It's funny that the buffer is marked as changed although not even a single character was changed.
