### ISSUE TITLE
What happened to #12? (Keystrokes)

### ISSUE THREAD

**Issue by d11wtq** [terryma/vim-multiple-cursors#38]
The README links to issue #12 for all the keystrokes used in the screencasts. That seems to 404 and I can't find it in the Issue history. I know I've read that issue before. Weird. Maybe GitHub is playing up, or has it been deleted (somehow)?

**Comment by ELLIOTTCABLE** [comment]
I question the choice to *delete entire conversations* when a user deletes their account. What the hell, @GitHub? O_O

… but also, the using of an Issue. What @chadoh said. ;)
