### ISSUE TITLE
Does not work with non-standard key mapping

### ISSUE THREAD

**Issue by varepsilon** [terryma/vim-multiple-cursors#46]
I have "i" mapped to "move right" (I think the standard for that is "l"). Nonetheless the plugin assumes that I have a default one and whenever I hit Edit (which is "s" in my case) after "C-n"ing couple positions, it **inserts** something like that:

`:call <SNR>164_apply_user_input_next('i')`

Is there any way to set it up correctly?

**Comment by still-dreaming-1** [comment]
Why was this closed? It claimed to be the duplicate of issue https://github.com/terryma/vim-multiple-cursors/issues/47, which seems like a separate issue to me, but no reason for closing was provided.

**Comment by faceleg** [comment]
Can't remember why I closed this, I should have left a comment. Apologies!

**Comment by antoinemadec** [comment]
@varepsilon @sheerun @still-dreaming-1 could you please update this plugin and let us know if you still see the issue ?
It should be fixed now... Just let us know!

**Comment by varepsilon** [comment]
Works for me, it seems.
