### ISSUE TITLE
Two cursor misalignment problems

### ISSUE THREAD

**Issue by jonahx** [terryma/vim-multiple-cursors#50]
I begin selecting words with a `ctrl-n` on the first "hello", and then hit `ctrl-n` a few more times to select the rest.  Note how the cursor on the first "hello" is one column too far to the right and misaligned from the others:

![top_cursor_misaligned](https://f.cloud.github.com/assets/699684/792932/62691e52-ebd0-11e2-9b9c-f606bf1e721d.PNG)

You can correct this problem if you remember to correct the first element before selecting the rest.  That is, `ctrl-n`, then `j` to correct it, then the remaining `ctrl-n`:

![even_selection](https://f.cloud.github.com/assets/699684/792931/6225cf12-ebd0-11e2-823e-dcc375e7f07a.PNG)

Now that everything is even i can type `v` for normal mode, move to the beginning of the word, and insert the word "jonah" by doing `ijonah `:
![insert words](https://f.cloud.github.com/assets/699684/792934/62d39854-ebd0-11e2-94d1-3b94287a603d.PNG)

Of course I have `g:multi_cursor_exit_from_insert_mode=0` so that I can escape and keep using all my cursors.  But uh-oh, as soon as I hit escape, the bottom cursor gets misaligned from the others, going one space to the left:

![bottom_misaligned_after_esc](https://f.cloud.github.com/assets/699684/792933/62aac186-ebd0-11e2-8b12-d2bff72ecde9.PNG)

**Comment by eapache** [comment]
The bottom-cursor misalignment was fixed in #109 - the top-cursors misalignment I have not been able to reproduce, so I am assuming it was fixed at some point in the past as well.

**Comment by faceleg** [comment]
Loving the activity on this repo! Lazarus repo.

**Comment by eapache** [comment]
I'm a lot more motivated to add patches when I know they'll be widely used :)

Thanks for reviving the original repository, and thanks @terryma for letting us play in your plugin :)
