### ISSUE TITLE
Conflict WIth AutoComplPop plugin

### ISSUE THREAD

**Issue by jonahx** [terryma/vim-multiple-cursors#51]
When using multiple cursors in insert mode, I'm seeing lots of errors with AutoComplPop plugin.  

This plugin provides command to enable/disable itself: `:AcpEnable` and `AcpDisable`.

Is there a way to hook a custom command into vim-multiple-cursors that gets triggered on any transition into or out of insert mode?  If not, how could I hack around this?

**Comment by credli** [comment]
Thanks @kristijanhusak, still fixes it in 2016
