### ISSUE TITLE
Editing multiple cursors is slow when large number of cursors

### ISSUE THREAD

**Issue by wichtounet** [terryma/vim-multiple-cursors#54]
Hi, 

I'm using vimified with vim-multiple-cursors. 

It works fine, but it is too slow when I use more than 5-6 cursors at the same time. When I use about 20 cursors, it takes about 1 second for entering a single character in insert mode. 

Is that normal behavior of the plugin ?

Thanks

**Comment by balta2ar** [comment]
This might be related: https://github.com/kristijanhusak/vim-multiple-cursors/issues/4.

**Comment by faceleg** [comment]
@balta2ar you're probably right - the solution for this situation is mentioned in the readme: https://github.com/terryma/vim-multiple-cursors#multiple_cursors_beforemultiple_cursors_after-default-nothing
