### ISSUE TITLE
How to avoid continous scrolling when replacing a word

### ISSUE THREAD

**Issue by fbrundu** [terryma/vim-multiple-cursors#58]
Hi,
suppose I am replacing n occurrences of a word with `<C-n> c` ..
If the word is distributed in a very long document vim jumps repeatedly from the start to the end of occurences every time I insert a new character. It wouldn't be more natural if vim focuses only on the first occurence while editing it?
Thanks

**Comment by faceleg** [comment]
It seems this has been fixed at some point.
