### ISSUE TITLE
select variable from different files in the same vim session

### ISSUE THREAD

**Issue by samuelololol** [terryma/vim-multiple-cursors#59]
the idea is from [AngularJS Brackets](https://www.youtube.com/watch?v=5ABAlfjkj3Q), will vim-multiple-cursors support this ??

**Comment by samuelololol** [comment]
Sorry, I didn't followup this thread.
What I mean is that will vim-multiple-cursors support cross-files selection and replacement as that it does in that video?

**Comment by faceleg** [comment]
No problem! No this plugin does not cross-files

**Comment by samuelololol** [comment]
will this feature be listed on future plan or wish list? it looks cool!
