### ISSUE TITLE
feature request: lazy editing

### ISSUE THREAD

**Issue by bling** [terryma/vim-multiple-cursors#61]
i think it'd be useful to have an option such that once you're in insert mode that it does *not* update every cursor after each keystroke.  this would solve a bunch of performance problems related to live updates.

basically, how `<C-v>jjjIfoo<Esc>` works.  thanks.

**Comment by balta2ar** [comment]
Duplicate of #58.

**Comment by faceleg** [comment]
Thanks @balta2ar
