### ISSUE TITLE
MultipleCursorsFind - upper / lowercase letters?

### ISSUE THREAD

**Issue by highend** [terryma/vim-multiple-cursors#63]
Hi,

Let's say I have variables like:
$thisDrive
$multipledrive

There doesn't seem to be a way to only select the lowercase "drive" parts.

At least
:MultipleCursorsFind drive

selects all matches, regardless if they have the upper- or lowercase "[dD]"...

Am I missing something?

**Comment by balta2ar** [comment]
@highend Looks like this is related to two vim options: `ignorecase` and `smartcase`. Try turning them off (`set noignorecase nosmartcase`) and repeat the command.

For the reason unknown to me this is only related to `MultipleCursorsFind`. In my environment `<C-n>` (`g:multi_cursor_start_key`) seem to ignore these two options. This might need further checks/investigation.

**Comment by faceleg** [comment]
Assuming this answered @highend's question
