### ISSUE TITLE
Can't get out of insert mode via arpeggio 'jk'

### ISSUE THREAD

**Issue by docwhat** [terryma/vim-multiple-cursors#67]
I use [arpeggio](https://github.com/kana/vim-arpeggio) -- specifically, I have this set up:

```vim

Arpeggio inoremap jk  <Esc>
```

This lets me press `jk` simultaneously instead of reaching for the `<Esc>` key.  Saves me lots of pain in my wrists.

However, if I use `Ctrl-n` to select a bunch of words, then press `c`; I cannot use `jk` to escape insert mode.

In addition, I sometimes notice characters are getting lost if I type fast.  It only happens when I enter insert mode via multiple-cursors.  I wonder if there is some issues with timers or something with arpeggio.

**Comment by benoittgt** [comment]
I've someone succeed to dot it. I'm interested. I've tried to remap `let g:multi_cursor_quit_key` without success.

**Comment by RX14** [comment]
I would also be interested in if someone managed to get `jk` to exit inset mode.

I have the following in my vimrc but it doesn't work:

```viml
" jk to exit insert mode
inoremap jk <ESC>
inoremap <ESC> <nop>
let g:multi_cursor_quit_key = 'jk'
let g:multi_cursor_insert_maps = {'j': 1}
```

**Comment by eapache** [comment]
> I would also be interested in if someone managed to get `jk` to exit insert mode.

It works for me, but I have a slightly different vimrc. For one thing, multi-character `g:multi_cursor_quit_key` is not supported, so you will not be able to get `jk` to exit multi-cursor mode entirely without major changes. Instead what I have is:

```viml
inoremap jk <esc>
let g:multi_cursor_exit_from_insert_mode=0
let g:multi_cursor_quit_key='q'
let g:multi_cursor_insert_maps={'j':1}
```

This successfully makes `jk` exit multi-cursor insert mode back into multi-cursor normal mode. I then have to press `q` to exit multi-cursor mode to go back to regular normal mode.
