### ISSUE TITLE
Quirks when switching v and CTRL-v mappings

### ISSUE THREAD

**Issue by gpakosz** [terryma/vim-multiple-cursors#70]
Hello,

When one has the following mappings:

```
" make v enter blockwise visual mode, and CTRL-V enter visual mode
nnoremap v <C-V>
nnoremap <C-V> v
vnoremap v <C-V>
vnoremap <C-V> v
```

Relying on `v` doesn't work. It doesn't trouble `Ctrl-n` because `exec "normal! viw"` still selects the word under cursor. But you can't go back to normal mode with `v` anymore. You have to use `Ctrl-v`.

Maybe `function! multiple_cursors#new(mode)` could take that use case into account? What do you think?

**Comment by faceleg** [comment]
Sounds interesting, how about a PR?
