### ISSUE TITLE
no visual mode with vim-airline

### ISSUE THREAD

**Issue by helmus** [terryma/vim-multiple-cursors#76]
vim v7.4
vim-airline v0.6
vim-multiple-cursors v2.2
putty 0.63

When i do ctrl-n multi selection works correctly. But my mode shows as NORMAL in vimair, I think it should be VISUAL ? If i press i get the error:

     Key 'i' cannot be replayed at 2 cursor locations

If i press v first it works correct. Not sure if this is a vimair issue or if i'm doing something wrong...

**Comment by Cbeck527** [comment]
Seeing the same issue here!

**Comment by faceleg** [comment]
Duplicate, see #42
