### ISSUE TITLE
[feature] support supertab module

### ISSUE THREAD

**Issue by Aluriak** [terryma/vim-multiple-cursors#78]
When have multi cursor and press tab with supertab module installed, the window opened by supertab is immediately closed. (impossible to read or navigate in it)

Don't know if this issue must be write there or with supertab issues.

supertab module : https://github.com/ervandew/supertab

**Comment by faceleg** [comment]
Doubt this will be fixed in this plugin.

**Comment by naggie** [comment]
I'd love this! @faceleg is a fix more possible in the [supertab](https://github.com/ervandew/supertab) plugin?
