### ISSUE TITLE
vim inserts garbage with multi cursors

### ISSUE THREAD

**Issue by timfeirg** [terryma/vim-multiple-cursors#81]
## symptom

when I enter insert mode with multiple cursors, all the letters I type become garbage like "<Plug>":

**what I type**
test
**what shows up**
te<Plug>s<Plug>t

this makes the plugin almost completely useless, I'm depressed as hell. but I need multi cursors very bad, hope there's a fix. TT
## my configuration

I would think this is something caused my other plugins or vim configurations, my [vimrc](https://github.com/kkcocogogo/osx-setup-for-developer/blob/master/.vimrc) is here, I didn't locate the plugin causing the problem yet, maybe it's something else.

**Comment by hookdump** [comment]
Hi. @kristijanhusak , YOU ROCK. <3

**Comment by aj07mm** [comment]
it's still appending garbage here. GNOME Terminal 3.18.3
