### ISSUE TITLE
Is it posible to evaluate each multi-cursor selection?

### ISSUE THREAD

**Issue by klonuo** [terryma/vim-multiple-cursors#83]
Hi,

I asked this on [StackOverflow](http://stackoverflow.com/questions/25088515/execute-statements-on-multiple-cursors-like-sts-minipy) but it turned out I better ask it here.

So, in Sublime Text I was using this [MiniPy](https://github.com/vim/MiniPy) plugin, which evaluates each multi-cursor selection through Python and replaces initial selection with the result.

Is it possible to do same with the help of this plugin?

**Comment by balta2ar** [comment]
@faceleg Why is this issue closed? I think this feature is nice and I'd like to have it. Let's keep it open as a reminder. Nobody ever glimpses over the closed issues, right (except of me right now)?
