### ISSUE TITLE
copy&paste not working

### ISSUE THREAD

**Issue by Hades32** [terryma/vim-multiple-cursors#89]
In IntelliJ I can have multiple selections, copy them, e.g. move the cursors 3 lines down and then paste the different lines. Vim currently just pastes the last line that was selected X times.

**Comment by jrolfs** [comment]
I know don't know VimL and have yet to dig into this codebase at all, but as far as I can tell this is the best bet for tracking down the visual selections: http://stackoverflow.com/a/6271254/530060

**Comment by balta2ar** [comment]
This would be amazing to have indeed. By the way, this behaviour makes people impressed (in a good way, I recon): https://github.com/neovim/neovim/issues/211#issuecomment-36887312
